### ISSUE TITLE
Cannot connect to local or remote bots

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#1023]
## Version
Latest V4 build - 4.1.0-preview-bugbash

## Describe the bug
Cannot connect to local or remote bots

## To Reproduce
1. Get set up with any sample from botbuilder-samples. Echo bot should do
2. Run the bot locally (or remote)
3. Open the bot file (or create a new one with the right endpoint information) and connect to the bot
4. Send messages from emulator

## Expected behavior
Emulator can connect to and exchanges messages with bot running locally or remote

[bug]

**Comment by justinwilaby** [comment]
I'm unable to repro this on a Mac.

**Comment by tonyanziano** [comment]
Can't repro on Windows either in version 4.1.0-preview-bugbash

**Comment by tonyanziano** [comment]
We figured out the issue. When using a localhost endpoint prefixed with `https` protocol (`https://localhost:3000/api/messages`) then the outgoing message hangs and eventually returns with I/O Socket error. We believe this is due to ngrok being confused about an https message without an ssl cert.

`request to https://localhost:3978/api/messages failed, reason: socket hang up`

Closing this issue, but we should work on at least notifying the user about this scenario and also work on removing the ngrok dependency for testing local bots.

#974
