### ISSUE TITLE
[LUIS instrumentation] Include emulator scenario x version identifier in User-Agent header on all calls to LUIS APIs

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#1086]
Is your feature request related to a problem? Please describe.
Today, we do not have any view into LUIS traffic that are driven by botbuilder. LUIS service instruments all calls to the service and can report on User-Agent to identify the specific client.

Describe the solution you'd like
On all calls to LUIS service (from the inspector including login, train, publish as well as reassign intent), include User-Agent header with the following value -
botbuilder/emulator/inspector/major.minor.patch.build
botbuilder/emulator/list-luis-apps/major.minor.patch.build

[enhancement]

**Comment by justinwilaby** [comment]
Should this be limited to just LUIS api calls? It might be appropriate to include user agent headers for all external traffic.

**Comment by tonyanziano** [comment]
What are the requirements for this item? 

While investigating this, I found out that Electron already appends `BotFrameworkEmulator/<version>` to the user-agent string.

If that's not sufficient, I also found a way to attach a custom user agent string to all outgoing traffic from the Emulator, but I'm wondering if we want a different string corresponding to the LUIS / QnA endpoint that is being hit. Or can we just include all the custom strings on every request?

Can LUIS & QnA just group the data on their side by the endpoint that was hit?

**Ex.**

> Luis receives 200 requests at `/api/.../train` with user-agent: `... BotFrameworkEmulator/4.1.0` so they can determine that users made 200 calls to train from the emulator.

Or do we need to include a specific string for each endpoint so that they can look at all the incoming requests across all their endpoints, and derive the action from the user-agent string?

**Ex.**

> Luis receives 200 requests with user-agent `... BotFrameworkEmulator/4.1.0 botbuilder/emulator/luis-train/4.1.0` so they can determine that users made 200 calls to train from the emulator

Fitting a custom user-agent string to each outgoing request from the emulator seems cumbersome.

**Comment by vishwacsena** [comment]
@tonyanziano - this is a broader effort across the SDK, CLI tools and Emulator and so we need the user-agent to be of the following format (I've also posted in the respective LUIS and QnA Maker tickets) 

botbuilder/<product>/<lang.or.scenario>/<semver>

So for Emulator, we would do the following
LUIS
botbuilder/emulator/inspector/major.minor.patch.build
botbuilder/emulator/list-luis-apps/major.minor.patch.build
and for QnA Maker
botbuilder/emulator/inspector/major.minor.patch.build
botbuilder/emulator/list-qnamaker-apps/major.minor.patch.build

We also do not need to include any additional information in the header. The specific command/ endpoint is instrumented and reported on both LUIS and QnA Maker side.

**Comment by tonyanziano** [comment]
Addressed in #1092 

===

There is no easy way for us to distinguish between calls made from the inspector, and calls made from the services flow without going into each call and adding on a custom user agent string, which would be tedious and fragile as the emulator grows. For now we will just add a custom user agent string of `botbuilder/emulator/version` to all outgoing requests.
