### ISSUE TITLE
Bot Emulator V4 using 127.0.0.1 instead of localhost

### ISSUE THREAD

**Issue by waleedabuyahia** [Microsoft/BotFramework-Emulator#1114]
When I connect to my bot which is running on IIS express, the Bot emulator could not send anything and I found that the issue is that emulator try to connect using 127.0.0.1 which my IIS Express is not binded to.

And I can not change my IIS express config because I do not have admin rights on my machine.

So when emulator tries to connect to 127.0.0.1 instead of local host it goes to our proxy. by the way same thing is working fine in emulator V3.5   

tryCatch.js:6 POST http://127.0.0.1:49583/v3/directline/conversations 403 (NoWebAccess-UnknownCategory)

**Comment by justinwilaby** [comment]
Hi @waleedabuyahia -

Using 127.0.0.1 is intentional since `localhost` still needs to be resolved to an IP address which can be overridden in the `hosts` file (on Windows) and can lead to undesirable side-effects.

Also, the address the emulator is listening on is the interceptor address for activities to and from WebChat which allows the emulator to display activity details. It's not the address used to connect to your bot. Configuring an endpoint is where you specify your bot's address. Once an endpoint is specified, the emulator forwards activities (such as messages typed in webchat) to that address.

The [wiki](https://github.com/Microsoft/BotFramework-Emulator/wiki) might be helpful in this case

**Comment by waleedabuyahia** [comment]
I understand this but why Emulator when the endpoint is localhost it
changes it to 127.0.0.1, this will not work with IIS express

**Comment by justinwilaby** [comment]
The emulator does not change the bot endpoint address. It sends message activity to the endpoint specified as is:

![image](https://user-images.githubusercontent.com/2652885/48798472-905e3c80-ecb9-11e8-94bf-c471ed5bc2ee.png)

There must be something else in your config that is causing this issue

**Comment by waleedabuyahia** [comment]
Yes it does not change the endpoint, but internaly it ceeates new
connection for the direct line using the 127.0.0.1

**Comment by vishwacsena** [comment]
Addressed via #1126
