### ISSUE TITLE
Emulator is taking a long time to startup

### ISSUE THREAD

**Issue by gabog** [Microsoft/BotFramework-Emulator#1118]
The emulator takes a very long to startup, is this a bug?

**Comment by justinwilaby** [comment]
How long is it taking? Windows machines take about 2-3x longer than Mac and Linux and Emulator installations with ngrok configured take a bit longer still but overall startup times don't exceed 4-5 seconds

**Comment by gabog** [comment]
I am running on windows, now that you asked and I tried to time it, it takes about 7-10 seconds but I've seen it take more. Sometimes i end up with 2 or 3 emulators running because I forgot I clicked on it. Will try to get a better repro (I am running 4.1.0)

**Comment by gabog** [comment]
Hi, I still don't have a repro for this, but I noticed that after a reboot it starts faster, then, startup gets slower over time.
Are there any logs somewhere that I can send you with details?
Right now, it is taking about 2 minutes and 16 seconds to start.

**Comment by mewa1024** [comment]
@tonyanziano @justinwilaby adding you both as assignees so yoo get updates on this thread. I'm happy to tackle this from the design (adding a splash screen or something) but was wondering if we're also looking into reducing the startup time.

**Comment by gabog** [comment]
Thanks @mewa1024, not sure what your alias is, ping me internally if you need more details.

Gabo

**Comment by tonyanziano** [comment]
@gabog Unfortunately we do not have any instrumentation or logs in place as of yet that track how long the startup process takes. That being said, starting up the application should never take more than 10 - 15 seconds, let alone minutes.

Could you please post the specs of your PC (CPU & RAM)? I'm curious because there was an issue posted over on the electron repo ([link here](https://github.com/electron/electron/issues/7902)]) where a user was experiencing the same long startup time with the electron demo app. It looks like certain machines with lower-end processors have trouble launching node and electron.

**Comment by gabog** [comment]
Hi Tony, here is a screenshot of my computer settings:
![image](https://user-images.githubusercontent.com/12264946/50296429-7b0b3800-0448-11e9-8913-5080208afeee.png)

I doubt is related to HW, it seems to work OK after a reboot but startup perf seems to get worse over time. The only other thing I have on my machine that runs on electron is Microsoft Teams but I don't know anything about electron and/or if there my be collisions with the runtimes.

Gabo

**Comment by tonyanziano** [comment]
Ok well I don't think it's hardware either. My machine has the same specs.

I will try to do some memory profiling locally and see if I notice anything unusual.

**Comment by justinwilaby** [comment]
I went ahead and profiled this on the main thread and didn't see anything that stood out. Startup times fell solidly between 4.7 and 5.2 seconds across 5 attempts. 

@gabog - Can you check your task manager to see if the Emulator process is hanging around after it has been closed? We had an ominous email from a user a few weeks back who said they saw the Emulator continuing to run even after it had been closed. I'm was not able to repro this but it seems likely this is what you have happening since a reboot fixes it then subsequent startups causes the problem to resurface.

**Comment by gabog** [comment]
Hi @justinwilaby , the issue is sporadic and hard to repro, I will take a look at task manager the next time it happens and will report back. 

Thanks
