### ISSUE TITLE
Speech stops working

### ISSUE THREAD

**Issue by gabog** [Microsoft/BotFramework-Emulator#1141]
## Version
4.1.0 (on windows)

## Describe the bug
Speech stops working after the emulator has been in use for a while. 
At some point, clicking on the mic icon doesn't enable the microphone anymore. 

## To Reproduce
I don't have specific repro steps, just use the emilator for a while (a couple of hours or more) and at some point the mic button should stop working.
The only workaround is to close and reopen the emulator (but it sometimes take a long to restart and it is a pain)

## Expected behavior
I would expect the mic button to work without having to restart the emulator.
[bug]

**Comment by justinwilaby** [comment]
This looks like a WebChat issue. @compulim  - is this a known issue for the WebChat version the Emulator is using?

**Comment by corinagum** [comment]
Bing Speech underwent a big [API update](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-migrate-from-bing-speech) to Speech Services back at this year's Ignite. Because of this, Bing Speech no longer allows the creation of new speech bots, and Bing Speech will be deprecated in 10/2019. 

Our plan is to have **Speech Services** supported (through the latest Web Chat) on Emulator very soon, and that progress can be tracked [here](https://github.com/Microsoft/BotFramework-Emulator/issues/1206). At the moment there is no plan to back-support Bing Speech in Emulator or Web Chat. For more information on Web Chat supporting Speech Services, please take a look at https://github.com/Microsoft/BotFramework-WebChat/issues/1336.

**Comment by gabog** [comment]
OK, I will wait for the new emulator but this issue is very similar with the an issue we have when using webchat on edge (it does work fine in chrome). Hopefully the rewrite to use the new API makes things better (but I wouldn't dismiss this as a Bing speech issue, there seems to be something else going on).

**Comment by corinagum** [comment]
@gabog if you are able to repro on Web Chat via Edge, this definitely sounds like a Web Chat issue - thanks for clarifying. Unfortunately I'm not able to transfer issues over to that repo -- if you manage to pin down more detailed reproduction steps, could you file this issue over there, listing those steps and any error messages you see in the console? Unfortunately debugging a bot that stops working after a few hours would be extremely difficult for us.
