### ISSUE TITLE
Chat log scroll bar doesn't render for bots connected via endpoint 

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotFramework-Emulator#1327]
## Version
Nightly: **4.2.149424**

## Describe the bug
Scroll bar in the chat view does not appear when connecting to a bot via endpoint:
![emulator-nightly-no-scroll-bar](https://user-images.githubusercontent.com/14935595/53360678-055d9580-38eb-11e9-8794-9fd2d816e370.jpg)

**Comment by justinwilaby** [comment]
@stevengum - This could be related to #1347 Can you confirm this is still an issue in the nightly?

**Comment by stevengum** [comment]
I don't have any bots setup with LUIS right now, but I can confirm the lack of a scroll bar for a full chat pane without any trace activities.

![no-trace-no-scroll](https://user-images.githubusercontent.com/14935595/53921122-38f39a80-4024-11e9-9384-971952f2db5b.jpg)

**Comment by tonyanziano** [comment]
This is due to a global style rule in the emulator. After changing it, the scrollbar appears:

**Before**
![image](https://user-images.githubusercontent.com/3452012/53987839-f50d9d80-40d6-11e9-934f-dc1715d18660.png)

**After**
![image](https://user-images.githubusercontent.com/3452012/53987798-d9a29280-40d6-11e9-85cf-efa227e79e3c.png)

**Result**
![image](https://user-images.githubusercontent.com/3452012/53987883-0eaee500-40d7-11e9-882f-0c3879aac855.png)

**Comment by tonyanziano** [comment]
Addressed in #1366
