### ISSUE TITLE
Test group conversation

### ISSUE THREAD

**Issue by bilby91** [Microsoft/BotFramework-Emulator#136]
I'm trying to test a group conversation for Skype.

Is there a way to test how the real payloads or docs for payload that you can receive when being added in a group conversation for example ?

Thanks!

**Comment by eanders-MS** [comment]
To make sure I understand your question: It sounds like you're trying to test the experience of receiving docs or attachments in group conversation in Skype. Is that correct?

**Comment by bilby91** [comment]
Nop, I'm trying to test the experience of my bot being added in a group conversation. Is that possible ?

**Comment by eanders-MS** [comment]
I see. That is not possible right now. Though the messages you'll receive in the emulator 1:1 case are very similar to what would happen in the group conversation:
- First, you'll receive a `conversationUpdate` activity with your bot in the `membersAdded` field.
- Second, you'll receive another `conversationUpdate` activity with the list of current members in the `membersAdded` field.

In any case, Skype's behavior may differ from the emulator. Due to differences between platforms, behavior is not uniform across all channels.

You should be able to run your bot locally and test this over Skype. Let me know if you'd like HOWTO details.

**Comment by bilby91** [comment]
@eanders-MS Please, info on the HOWTO is more than welcome!

**Comment by eanders-MS** [comment]
Sure, here's a quick summary (I don't think we've written this up yet):
1. Register your bot with the Bot Framework. Don't worry about providing a valid endpoint yet. Anything starting with `https://` will be accepted.
2. If you haven't already done so, download [ngrok](https://ngrok.com/download) and copy it to a permanent location on your local machine (mine lives at `C:\ngrok\`).
3. Start your bot. Make a note of the port it is listening on (typically 3978, but not guaranteed).
4. On a command line, start ngrok with these parameters: `ngrok http -host-header=rewrite $(port)`, replacing $(port) with the port number your bot is listening on.
5. Once ngrok has started up, it will print out the public endpoints it has opened up for you. Copy the `https` endpoint to the clipboard. It will look something like `https://xxxxxx.ngrok.io/`. This will be part of your bot endpoint. Your entire bot endpoint will look like this: `https://xxxxxx.ngrok.io/api/messages`
6. Edit your Bot Framework bot registration, configuring it with your ngrok-based endpoint.
7. Enable the Skype channel and any other channels you wish to test from.
8. That should be it!

**Comment by bilby91** [comment]
@eanders-MS Thanks for the tip! Worked perfectly!
