### ISSUE TITLE
Please add local directLine websocket handling into the Bot Emulator Framework

### ISSUE THREAD

**Issue by vseanclark** [microsoft/BotFramework-Emulator#1405]
We have implemented a custom channel that is dependent on the directLine messages via the websocket.  When running with the Bot Emulator Framework locally, we do not receive these websocket messages as documented.  Because of this, our local code behaves differently than the code when executed in the cloud.  

Our enterprise policy does not allow using NGROK as the suggested workaround for this issue.

We request the addition of the local directLine websocket handling into the Bot Emulator Framework.

**Comment by justinwilaby** [comment]
DirectLine is undergoing a major overhaul which may mandate the use of websockets. Once this is fully baked, we will implement the new protocol in the Emulator. 

With that said, I will open a discussion with the team about whether or not we want to implement the existing protocol via websockets. In the meantime, keep an eye on #1394 since this feature will allow you to use any channel for locally running bots including direct line via web sockets and sill connect to the Emulator.

**Comment by tonyanziano** [comment]
@vseanclark we have just merged in a PR (#2034) that switches communication between the client (Web Chat) and the Emulator to Web Sockets instead of REST polling via GET.

It may be worth checking out to see if it resolves your issues.

It will be available in the newest nightly at around 10:30 PM PST tonight.

**Comment by cwhitten** [comment]
Closing as fixed!
