### ISSUE TITLE
[DCR] Open Emulator via url protocol. Ex: botemulator://localhost:3978/api/messages

### ISSUE THREAD

**Issue by mdrichardson** [Microsoft/BotFramework-Emulator#1420]
**Is your feature request related to a problem? Please describe.**
With `.bot` files going away, it's *somewhat* painful to Open Emulator > Open Bot > manually type `http://localhost:3978/api/messages` every time.

**Describe the solution you'd like**
I would love for a bot to startup with something like:

```
restify listening to http://[::]:3978

Open in Emulator: botframeworkemulator://localhost:3978/api/messages   // <--clickable link
```

**Describe alternatives you've considered**
This idea: #609 

**Additional context**

This would need to be integrates with samples + install of Emulator.

[This appears to be supported in VS Code](https://code.visualstudio.com/updates/v1_26#_uri-handler-api)

[Microsoft Docs on URL protocols](https://msdn.microsoft.com/en-us/windows/desktop/aa767914)

[enhancement]

**Comment by tonyanziano** [comment]
Hey @mdrichardson ,

This actually is a feature that's already implemented in the Emulator ([source here](https://github.com/Microsoft/BotFramework-Emulator/blob/master/packages/app/main/src/protocolHandler.ts)), however I have just tried it and it appears to have regressed due to a change to how the ngrok instance is started within the emulator.

We currently lack documentation on this feature, but this is the schema for opening a livechat with a bot from protocol:

`bfemulator://livechat.open?botUrl=url[&msaAppId=id][&msaPassword=pw][&secret=secret]`

where each query parameter's value is URI encoded. Here is an example for talking to a bot with the endpoint `http://localhost:3978/api/messages`:

`bfemulator://livechat.open?botUrl=http%3A%2F%2Flocalhost%3A3978%2Fapi%2Fmessages`

**Comment by tonyanziano** [comment]
I'll keep this open until the regression gets fixed.

**Comment by tonyanziano** [comment]
I have a fix in a local branch. Going to wait until the sidecar debugging work (#1394) goes in.
