### ISSUE TITLE
Inconsistent User ID for "Restart Conversation"

### ISSUE THREAD

**Issue by ravriel** [Microsoft/BotFramework-Emulator#1448]
## Version
4.3.3

## Describe the bug
The Bot Emulator generates a new Activity.From.Id each time "Restart Conversation" is pressed.

Since the UserState is keyed on this ID, a new UserState is generated each time, instead of retrieving the existing UserState.

Note that if emulator is closed and re-opened then the ID remains consistent.

## To Reproduce
1. Take note of ID1 from Activity.From.Id in bot.
2. Click on 'Restart Conversation'
3. Take note of ID2 from  Activity.From.Id in bot.
4. ID1 is different from ID2.

## Expected behavior
User ID should remain consistent across "Restart Conversation", otherwise UserState cannot be used.

## Additional context

[bug]

**Comment by cwhitten** [comment]
@ravriel when you restart the conversation, are you selecting the option to reuse the same user id? 

<img width="373" alt="Screen Shot 2019-04-23 at 8 47 37 AM" src="https://user-images.githubusercontent.com/1156704/56595960-78f6e880-65a4-11e9-8e85-a14148607033.png">

**Comment by ravriel** [comment]
Sorry, I wasn't aware of the these two options. 
I just pressed the button that, apparently, creates a new user ID.

**Comment by snapfisher** [comment]
I as going to have the same complaint.  I'm glad I saw this.  However, I think the issue is that the default action should be to use the same ID.  On the button and if the emulator is restarted.  New IDs should be generated only if requested through the drop down.  This will make the emulator more consistent, both in general and in respect to previous versions
