### ISSUE TITLE
Unable to create a package of the app

### ISSUE THREAD

**Issue by denscollo** [microsoft/BotFramework-Emulator#1560]
## Version
Emulator 4.4.x
Windows 10

## Describe the bug
Right now, when we are testing the solution for the issue # 1136 we want to package the app on `master`. However, running the commands for that is throwing an error that we do not find in older branches.

## To Reproduce
1. Checkout `master`
2. Build the app from source
3. Package the source: cd packages/app/main & npm run dist -- --win 
4. You will get the error `Get $%7Benv.ELECTRON_MIRROR%7D4.1.1/electron-v4.1.1-win32-ia32.zip: unsupported protocol scheme`

## Expected behavior
Create the packaged version of the current local state of the aplication

## Screenshots
Screenshot of the full error:
![imagen](https://user-images.githubusercontent.com/22912283/57533420-1deb2280-7314-11e9-909a-0ca3d25aa8e2.png)

**Comment by justinwilaby** [comment]
Have you tried running `npm run dist` in `/packages/app/main`?

**Comment by tonyanziano** [comment]
Oh, I actually know what this is. I can fix this.

**Comment by tonyanziano** [comment]
Actually, after looking at this, I'm not sure what's causing this. I thought that maybe the environment variable for the electron mirror was accidentally set somewhere, but that's not the case.

It looks like electron-builder is trying to use the correct electron mirror, but it is trying parse the `{env.ELECTRON_MIRROR}` from main's `package.json`, instead of seeing that it is undefined and defaulting to the standard mirror.

Can you type `set` in your terminal and see if the `ELECTRON_MIRROR` is somehow set? If so, I would try and clear it. Also, I'm not sure this will make a difference, but try what Justin suggested, and run `npm run dist` instead of calling `electron-builder` directly.

**Comment by denscollo** [comment]
Hi @tonyanziano , we checked our environment and the {env.ELECTRON_MIRROR} was not declared. We also ran some tests and noticed that the variable in the package.json is returning the textual name of the variable when it's not declared, so it only works when {env.ELECTRON_MIRROR} has been declared and has a value.

We were able to make it work by removing the electron download mirror. We believe this should be removed. If you agree we can make a PR with this change.

**Comment by tonyanziano** [comment]
Hey @denscollo,

I'll have to check and see if removing the download mirror from the `package.json` would have side effects in the packaging process, because it is currently used by the build process to download a custom, internal build of Electron from a Microsoft server.
