### ISSUE TITLE
Conversations in transcript mode do not always render the chat control

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1623]
## Version
4.4.2

## Describe the bug
Opening a conversation in transcript mode sometimes does not render the chat control.

## To Reproduce
1. Open a .transcript file
2. Possible see no or delayed rendering of the chat control.

## Expected behavior
The chat control should render like any other conversation mode

## Screenshots
![image002](https://user-images.githubusercontent.com/1156704/59222103-96483c00-8b7d-11e9-9329-e5d6cd5f5d16.jpg)

## Additional context
From Lars Liden:
> So I re-opened the Emulator from the background after working on other stuff and the chat was there.  I tried importing another .transcript file and saw the blank panel again.  If you wait long enough it appears, but after quite a delay.

ping @cwhitten if you cannot reproduce with a .transcript file of your own

[bug]

**Comment by tonyanziano** [comment]
I was finally able to repro this, and I believe it's due to the fact that the Emulator is waiting for the Direct Line instance to initialize before piping all the conversations into Web Chat.

I'm able to reliably repro it by double clicking a transcript file when the Emulator is not running. I'm then able to open the Network tab in the dev tools, and as soon as the 200 comes back from the `/v3/directline/conversations` endpoint, the chat control renders with all the activities.
