### ISSUE TITLE
Error: connect ETIMEDOUT 40.112.254.71:443

### ISSUE THREAD

**Issue by ne00346536** [Microsoft/BotFramework-Emulator#167]
Hi 

We are developing bot in Node JS , I  am able to connect to bot emulator without app id and password  but the problem is when I  send message to bot its not able to acknowledge the reply , In node JS console its returning the following error.

Emulator URL 
http://localhost:3978/api/messages

Node JS console logs.
--------------
restify listening to http://[::]:3978
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
session.beginDialog(/)
/ - session.sendBatch() sending 0 messages
/ - session.error()
/ - session.endConversation()
session.sendBatch() sending 1 messages
**# ## **Error: connect **ETIMEDOUT 40.112.254.71:443******
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)

Emulator logs
---------
[16:17:30] -> POST 202 [message] hi 
[16:17:30] <- GET 200 getUserData 
[16:17:30] <- GET 200 getPrivateConversationData 
[16:17:55] <- POST 200 setPrivateConversationData 
[16:18:18] <- POST 200 setPrivateConversationData 
[16:18:18] <- POST 200 Reply[message] Oops. Something went wrong and we need to start ov...

We are working behind a proxy and corporate firewall , can you please let me know the details how to fix this issue.

I configured ngrok path in emulator settings not sure how to verify the same . When we test the code through open network able to get the response from bot.

Thanks

**Comment by ne00346536** [comment]
Hi,

Can someone provide details on this issue.

Thanks

**Comment by eanders-MS** [comment]
Your bot appears to be having some success sending messages to the emulator:

> [16:17:30] <- GET 200 getUserData
> [16:17:30] <- GET 200 getPrivateConversationData
> [16:17:55] <- POST 200 setPrivateConversationData
> [16:18:18] <- POST 200 setPrivateConversationData
> [16:18:18] <- POST 200 Reply[message] Oops. Something went wrong and we need to start ov...

The port number on this address is giving me pause, because it's https:

> 40.112.254.71:443

This may be the SDK trying to contact the authentication service. Are you securing the connection with AppId and Password? The log entry below leads me to believe you aren't, but want to be certain:

> WARN: ChatConnector: receive - emulator running without security enabled.

If you are running without credentials, please double-check they're cleared from both the bot's environment and from the emulator.

@Stevenic, is there any case where the BotBuilder Node SDK will try to hit the auth endpoints when running without credentials?

@ne00346536 What is the serviceUrl the emulator is sending to the bot? You can find it by going to the log view and clicking on any of the messages sent to the bot.

**Comment by ne00346536** [comment]
@eanders-MS , I cross verified yes I removed credentials then only bot connectivity is success which we can see in logs shared. but i am getting error when we try to chat with bot message is delivered but its not able to acknowledge.

Thanks.

**Comment by eanders-MS** [comment]
Is your bot running on a different machine than the emulator?

**Comment by ne00346536** [comment]
@eanders-MS  bot running on the same machine and the URL is http://localhost:3978/api/messages  and i am testing the bot in emulator.

service URL when the message sent is as follows

serviceUrl": "http://localhost:62324

log message when its not able to acknowledge 

{
  "type": "message",
  "text": "Oops. Something went wrong and we need to start over.",
  "locale": "en-US",
  "from": {
    "id": "default-bot",
    "name": "Bot"
  },
  "recipient": {
    "id": "default-user",
    "name": "User"
  },
  "id": null,
  "replyToId": "40h7dh46e72g6a69"
}

[10:54:19] <- POST 200 setPrivateConversationData 
[10:54:44] <- POST 200 setPrivateConversationData 
[10:54:44] <- POST 200 Reply[message] Oops. Something went wrong and we need to start ov...

Thanks.

**Comment by eanders-MS** [comment]
The bot is communicating with the emulator successfully, but it's also trying to connect to 40.112.254.71:443 for some purpose (likely trying to hit the auth verification endpoint). The failure from that attempt is resulting in the bot sending the "Oops. Something went wrong..." message to the emulator.

Since you have the repro, would you mind doing a little bit of sleuthing? If yes, then in the debugger your bot is running in, set a breakpoint in the BotBuilder SDK at node_modules/botbuilder/lib/core/bots/OpenIdMetadata.js, around line 12, at the top of this method:

``` javascript
OpenIdMetadata.prototype.getKey
```

If your breakpoint gets hit, please post the callstack here.

Another thing you could do is run [fiddler](https://www.telerik.com/download/fiddler) (it's a tool for network debugging, in case you're not familiar), configure your proxy settings to NOT bypass for local addresses (see image below for how to configure for this), and capture a message sent from the emulator to the bot. In particular, I'd be interested to see its message headers.

Your assistance is appreciated!

![image](https://cloud.githubusercontent.com/assets/12176807/25470102/3d35e910-2ad5-11e7-9169-9a210561c10d.png)

**Comment by eanders-MS** [comment]
Going ahead and closing this now. If you'd like further assistance, reply here and we'll reopen it.

**Comment by haripulaparthi** [comment]
HI I am also facing the same issue can any one please help me ? Here i am using .net sdk.

Error Log Details:

************************************

"innerException": {
    "message": "An error has occurred.",
    "exceptionMessage": "Unable to connect to the remote server",
    "exceptionType": "System.Net.WebException",
    "stackTrace": "   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)",
    "innerException": {
      "message": "An error has occurred.",
      "exceptionMessage": "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.112.254.71:443",
      "exceptionType": "System.Net.Sockets.SocketException",
      "stackTrace": "   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)"

**Comment by Sankaraiah-burra** [comment]
@ne00346536 provide appid and pwd in both .env file and in emulator, then it will work
