### ISSUE TITLE
Error Payloads Displayed as One-Character-Per-Line HTML Page

### ISSUE THREAD

**Issue by RobRoseKnows** [microsoft/BotFramework-Emulator#1673]
I'm trying to debug a bot using C# right now but I'm having an issue with the emulator. The HTML response ([see HAR](https://gist.github.com/RobRoseKnows/29fc52a78b0b7f32edbf10c4bf913632)) is being turned into [this](https://gist.github.com/RobRoseKnows/2adb0a1224dd2ea16eb8ee3ebf5eb5ae) JSON response. According to devtools, the response type is JSON, but the body is just HTML in a string. Would be nice to be able to reformat that manually.

[bug]

**Comment by tonyanziano** [comment]
Hey @RobRoseKnows ,

Thanks for the report. We've had several reports of this behavior where the error response payload in the Emulator is displayed as this HTML page with one character per key. We thought it was fixed in a previous PR, but it looks like it's still happening.

I'll confirm this as a bug and see if we can slot it for our next development cycle.

**Comment by tonyanziano** [comment]
For fixer:

See also: https://github.com/microsoft/BotFramework-Emulator/issues/1664#issuecomment-507902435
