### ISSUE TITLE
Bot Emulator no longer answering to user

### ISSUE THREAD

**Issue by Zack-Strife** [microsoft/BotFramework-Emulator#1688]
Hello,

yesterday I updated from 4.2 to 4.5.1, since then, it seems that my bot can't recognize any user input. 
For reference, my bot is written in TypeScript and based of the Virtual Assistant Skill template. 

I tried reverting my code to the last working Master push, uninstalling Bot Emulator and re-installing in 4.2, re-creating a new Virtual Assistant with everything updated (all libs, the bot emulator, and a fresh new Virtual Assistant) but still nothing.
![Bot_Framework_Emulator_2019-07-16_16-23-43](https://user-images.githubusercontent.com/16171988/61302475-1f3e3d00-a7e6-11e9-9fe7-90d85a68869a.png)
Here's a screen from the fresh Virtual Assistant that should be answering.

I've checked and we do enter the turn() in dialogBot.ts but I think that's as far as we make it, and since I've tried with code that worked before and with a fresh new virtual assistant just installed, I'm wondering if this is coming from the data the bot emulator send to the bot ?

Microsoft App Id and Password are good, no ngrok channel for the VA and checked them on my skill, nothing wrong with them

Am I the only one with this issue ? If I am is there any cache or something preventing me to go back to 4.2 the exact way it was before ?
Thanks

**Comment by tonyanziano** [comment]
Hi @Zack-Strife ,

Judging from your description, it sounds like the problem is originating from your bot. If you completely wiped your install of the Emulator, went back to the old version it was working on and it still doesn't respond, then it's probably a problem with the bot or your configuration.

You can try going to the `%APPDATA%` on your machine and deleting the `/@bfemulator/` directory and installing the Emulator again, but I'm not confident that will fix your issue.

**Comment by Zack-Strife** [comment]
Thanks for your time, tried to delete everything without success, tried to debug it with the debugger too without success.

Managed to make a simple Echo Bot and Core Bot works on the emulator so the problem is probably not linke to the emulator as you said.
