### ISSUE TITLE
Introduce a context menu -> copy JSON in the JSON inspector

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1699]
With the collapsible JSON extension, users lost the ability to easily copy the payload. We'll introduce functionality for them to get the JSON data on their clipboard.

1. Right clicking on the activity in the chat control
2. A button in the inspector itself allowing the user to copy the raw data
3. a context-menu somewhere inside the extension with the option to copy

see #1694

**Comment by cwhitten** [comment]
@mewa1024 can you comment on one of the three options we have available to us above?

**Comment by mewa1024** [comment]
I like option 2. The button should say "Copy" and have no icon (to avoid a proliferation of icons when in sidecar mode).

Longterm, can w consider another Pivot that says "RAW JSON", which allows the user switch between views, similar to this view in Firefox?
![image](https://user-images.githubusercontent.com/39317542/61979090-bdc95b80-afa7-11e9-961d-8cc05ab7c231.png)

mockup:
![image](https://user-images.githubusercontent.com/39317542/61979361-7b544e80-afa8-11e9-
![image](https://user-images.githubusercontent.com/39317542/61979537-fc134a80-afa8-11e9-9a8e-0f4ee7ae6f39.png)

**Comment by tonyanziano** [comment]
Note to fixer (@denscollo ):

It looks like this is already implemented for all activity types -- Activity, Trace, Command -- when the livechat session is in debug (inspector) mode:

![image](https://user-images.githubusercontent.com/3452012/62251521-dd47f600-b3a4-11e9-997a-42a6a7b1685f.png)

However, it is disabled for livechat sessions in default mode. @cwhitten do you happen to know if that was an intentional design decision for inspector mode only?

If not, I don't see any harm in enabling the same context menu for activities in default mode;

The function responsible for initiating the context menu in `chat.tsx` can be found [here](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx#L283) and the chat saga that eventually contacts the main process to show the menu can be found [here](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/app/client/src/data/sagas/chatSagas.ts#L81).

**Comment by cwhitten** [comment]
Let's go ahead and wire up the Copy button as @mewa1024 suggests, and show the `Copy json` menu item on all activity types regardless of connection mode.

**Comment by tonyanziano** [comment]
Addressed in #1801
