### ISSUE TITLE
Implement custom activity generator

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1700]
see #416 

Functionality currently in the Send System Activity menu is spotty at best.  This ticket represents addressing issues causing any broken behavior in the activities to be sent & provides a place to send an arbitrary activity payload to the bot.

**Comment by xieofxie** [comment]
Do we have a timeline for this 'provides a place to send an arbitrary activity payload to the bot'?
It is quite useful, thanks~

**Comment by tonyanziano** [comment]
@xieofxie it is scheduled for our current release schedule (March release), but it has a lower priority so it may get bumped depending on the progress of other scheduled tasks for this release.

**Comment by RenanCarso** [comment]
Waiting for this feature...

**Comment by tonyanziano** [comment]
Sorry @RenanCarso ,

This was scheduled to be in our 4.9.0 release, but we had to re-prioritize the issue due to resources being needed on another project.

It's possible that this gets scheduled as a work item for our 4.10.0 (R10) release. However we have not yet held the planning meeting for R10 that will dictate the R10 work items.

We understand that this is a pretty sought-after feature, and it is on our radar. If we do decide to take this for the next release, this ticket will be tagged and updated appropriately.

**Comment by tonyanziano** [comment]
Suggestion from an email thread:

It would also be great if on top of this feature, we could build a sort of "collections" system that would allow users to save previous payloads or organized lists of payloads so that they could easily send them again.

This would be similar to the "Collections" feature in Postman.

**Comment by peterbozso** [comment]
I am looking forward to this feature very much.

To others who are stumbling into this issue in the meanwhile, I created [this Postman package](https://github.com/BotBuilderCommunity/botbuilder-community-tools/blob/master/directline-postman/README.md) that you can use instead of the Emulator to test custom events through the Direct Line.

**Comment by tonyanziano** [comment]
This feature will be available in tonight's nightly build. Check out #2213 for details

**Comment by tonyanziano** [comment]
The latest nightly here includes this feature: https://github.com/microsoft/botframework-emulator-nightlies/releases/tag/v4.11.0-199884
