### ISSUE TITLE
Adaptive Card content is cleared on submit

### ISSUE THREAD

**Issue by sachabruttin** [microsoft/BotFramework-Emulator#1701]
## Version
4.5.2

## Describe the bug
Since version 4.5.0 the adaptive cards are behaving incorrectly. Version 4.5.1 and 4.5.2 have fixes for the issues #1680 and #1683 but the experience is still not at the same level as 4.4.2.  

On 4.5.2 the form content is cleared on submit. Sometimes the data are correctly sent back to the bot, sometimes not. 

## Screenshots
See the difference between 4.4.2 and 4.52

### Version 4.4.2
![emulator-4 4 2](https://user-images.githubusercontent.com/2523409/62208187-6b68b000-b396-11e9-9d31-f4eafc582ca4.gif)

### Version 4.5.2
![emulator-4 5 2](https://user-images.githubusercontent.com/2523409/62208222-7de2e980-b396-11e9-963e-ed30cdfe7744.gif)

## Expected behavior
Form value must not be cleared on Adaptive Card

[bug]

**Comment by tonyanziano** [comment]
HI @sachabruttin ,

Thanks for reporting.

I was aware of the form being cleared when the submit button was pressed, however, I did not realize that it was possible that the activity did not contain the form data when sent to the bot.

I'll investigate.

**Comment by tonyanziano** [comment]
Hello @sachabruttin ,

I've been trying to reproduce the issue, and as expected the forms inside of the Adaptive Cards due clear on Submit, however, I could not reproduce the scenario in which the form data was not being sent to the bot.

The form being cleared is a current limitation of the way we render Web Chat within the Emulator, but the data should be correctly relayed to your bot upon pressing submit.

Do you happen to have steps for a reliable repro of the form data not being correctly transmitted to the bot?

**Comment by sachabruttin** [comment]
Hello @tonyanziano 

This not easy to reproduce because it occurs randomly. Please check these 2 videos.

![clean-before-submit](https://user-images.githubusercontent.com/2523409/62999333-67489200-be6e-11e9-8a3b-3630ce87465a.gif)

I suspect the form data is not correctly submitted because the card is cleared before I click on the submit button. 

On the next one, the dropdown is cleared just after I have selected a value...
![dropdop-clean-onselect](https://user-images.githubusercontent.com/2523409/62999377-86dfba80-be6e-11e9-8fb8-e4dc4e9ae94d.gif)

As previously state, all these behaviors were not present on the 4.4.x release. Is there something that prevents you from rollback the rendering of the Adaptive Cards to the working one?

**Comment by tonyanziano** [comment]
@sachabruttin Thank you for posting the recordings. From the looks of those gifs, it looks the root of the issue is still due to the forms being cleared and not the actual transmission of the form values to the bot.

What I can see from both your gifs is that both forms are cleared at the same time as a 

`POST 200 directline.postActivity`  

appears in the log panel. I think the addition of a

**Comment by tonyanziano** [comment]
*Notes to fixer:*

- re-render looks like it's caused by any state changes at all to the chat document associated with the livechat
- potential fix could be to flatten out different parts of inner chat document structure into separate state slices so that a change within the chat document doesn't affect every component connected to the chat at the root level
