### ISSUE TITLE
Getting Forbidden error when connecting to bot emulator

### ISSUE THREAD

**Issue by ragavendrach13** [microsoft/BotFramework-Emulator#1702]

**Comment by ragavendrach13** [comment]
I'm getting error as, Error occurened while opening bot at http://localhost:3978/api/messages: Forbidden.
I have downloaded a echobot template and tried to build it.

**Comment by tonyanziano** [comment]
Hi @ragavendrach13 ,

It's very difficult to diagnose your issue without more information or screenshots.

What steps have you used to start your bot and also to connect the Emulator to your bot?

At the moment, the information you have provided does not lead me to believe that the problem is caused by the Emulator.

Feel free to [ask for help over on Stack Overflow](https://stackoverflow.com/questions/tagged/botframework). Once you gather some more information that can narrow the cause down to the Emulator, feel free to reopen this issue and post your findings here.

**Comment by ragavendrach13** [comment]
Dear tony, please find the details as requested.
Steps to reproduce:
1. Installed Bot Framework SDK v4 template for C# in visual studio 2019.
2. Created a new echo bot template project.
3. Click on Run in IIS Express. 
4. I get the message as  
" Your bot is ready!
You can test your bot in the Bot Framework Emulator
by connecting to http://localhost:3978/api/messages"
5. I then opened my bot emulator, in welcome page i clicked on Open bot and I gave bot URL as
http://localhost:3978/api/messages and clicked on connect.
I get an error as Unable to connect to http://localhost:3978/api/messages  : Forbidden. in Notifications window
Kindly help on this issue.
