### ISSUE TITLE
[MAS4.2.8] [Programmatic and access -Settings] An element of the given Control Type must support the Text pattern for “User ID” text field.

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1767]
**Actual Result:**
An element of the given Control Type doesn’t support the Text pattern for “User ID” text field. 

**Expected Result:**
An element of the given Control Type must support the Text pattern for “User ID” text field.

**How To Fix:** 1. Make sure the element has the appropriate Control Type property for its function.
2. If the current Control Type is correct, modify the element to support the Text pattern.

**Repro Steps:**
1.	Open the Bot Framework V4 Emulator.
2.	Navigate to Welcome tab screen and select it, screen gets opened  
3.	Navigate to the open bot and select it  
4.	Open bot dialog gets opened and connect to the open bot 
5.	Live chat screen gets appears 
6.	Navigate to the Edit ngrok settings and select it 
7.	Emulator screen gets opened 
8.	Run the accessibility insights for windows tool
9.	Observe the issue

**User Impact:**
users who rely on AT will be affected if programmatically control type is not defined properly so the AT users will misguide the information

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator
Tools: Accessibility insights for Windows

**MAS Reference Link:**
[Sharepoint Link](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={2f57ba18-487d-4adc-a077-377be980e7d5})

![MAS4 2 8_Settings](https://user-images.githubusercontent.com/53518994/63507615-c30dbd80-c4f5-11e9-970c-5b5a4606aad0.png)

**Comment by tonyanziano** [comment]
The problem here is unclear to me, and I'm not sure how to proceed with fixing this.

I downloaded Accessibility Insights for Windows and scanned the same page, and all the other text fields on the same page show the same properties, but they aren't showing any test errors in the tool.

> 1. Make sure the element has the appropriate ControlType property for its function.
2. If the current ControlType is correct, modify the element to support the Text pattern.

What is a ControlType and how does it translate to HTML markup? If the ControlType is correct, what is the Text pattern and how does that translate to HTML?

**Comment by Kumar2608** [comment]
As directed by customer, electron app wont support Accessibility Insights for Windows
hence we are closing this bug .
