### ISSUE TITLE
Emulator chat pane out of sync with activity (on activity pane)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Emulator#1789]
Bot responses showing in activity trace window, but aren't rendering in the chat window. See image.

![image](https://user-images.githubusercontent.com/8867670/63894159-ce069900-c9a0-11e9-8243-513185450f38.png)

![image](https://user-images.githubusercontent.com/8867670/63894350-42413c80-c9a1-11e9-8ecf-f11b0aeb9733.png)

**Comment by tonyanziano** [comment]
@scheyal can you provide some more information around how you arrived at this scenario?

I see that all the failed sends happen after your bot spits out what looks like an exception: `"Value cannot be null. Parameter name: o`

Is it possible that your bot stopped running after it hit the exception, and all the failed sends are because your bot is returning 500s?

**Comment by cwhitten** [comment]
@scheyal we're going to close this for now. We think something may be wrong with your bot that is causing this.
