### ISSUE TITLE
[Functional - Open Bot Dialog] The focus goes on the disabled controls and functioning by space/return.

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1890]
**Actual Result:**
In voiceover mode, the focus lands on the disabled control such as "Connect" button. The voiceover informs that the controls are disabled but if the user accidently press "spacebar" or "return" key the pane gets closed.

**Expected Result:**
As the controls are disabled, they shouldn't be active or accessed by any key.

**Note:**
Same issue observed at every disabled controls present throughout the application.

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Navigate to the "Open Bot Dialog" button and activate it.
4. Open Bot Dialog box gets opened.
5. Navigate to the dialog box in voiceover mode and select "Connect" disabled button.
6. Try to activate the button with "Spacebar" or "Enter".
7. Observe the issue.

**User Impact:**
If the disabled controls are accessible by keyboard the user might get confused.

**Test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-80829)

**Attachment:**
[Disabled control are functioning.zip](https://github.com/microsoft/BotFramework-Emulator/files/3676372/Disabled.control.are.functioning.zip)

**Comment by tonyanziano** [comment]
Is it recommended to completely hide disabled controls from the screen reader? Or is it better to have them be accessible by the screen reader, but not functional when pressed.

The latter case seems to make more sense to me because, wouldn't you want the non-sighted user to know about all the inputs on the screen? If a disabled buttons becomes enabled after filling out a form, how would the user know it has been enabled if they never knew it was there to begin with?

**Comment by ShikhaMishra11** [comment]
@tonyanziano As i verified in the latest build of BotFramework Emulator, now the focus didn't lands on the disabled control. I guess it is fixed with #1910 

**Test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (version: 4.6.0-92058)

**Comment by tonyanziano** [comment]
Closing due to above comment.
