### ISSUE TITLE
the confirmed open URL is not opening in web browser 

### ISSUE THREAD

**Issue by mouhannadali** [microsoft/BotFramework-Emulator#1891]
after I have configured the Auth using GenericOauth2 when I click login, the following message appears:
![image](https://user-images.githubusercontent.com/17967903/66042263-4a4e4800-e51c-11e9-9d2f-ea1a91f6cc06.png)

when I confirm, I expecting an new webpage will be opened  to sign in. something like this:
![image](https://user-images.githubusercontent.com/17967903/66042830-d745d100-e51d-11e9-97e9-99e00b9d2074.png)

but what is happening is that a new emulator window is opened but with missing controls screen: 
![image](https://user-images.githubusercontent.com/17967903/66042780-b5e4e500-e51d-11e9-8cab-a8602d352bfb.png)

anybody can help how to solve this issue ?

**Comment by tonyanziano** [comment]
Hi @mouhannadali ,

This might be due to the fact that in version 4.5.2 NodeJS integration is enabled in all Electron windows. Which means that if we open a new Emulator window such as the one in your example, and there are conflicts between JS libraries used in the window and globals used by the NodeJS runtime, then it can cause an error and a blank screen.

We had a recent PR (#1839) that addressed ths, but is not in a stable release yet. This change will be in the next stable release, v4.6.0, but if you don't want to wait, you can try using the [latest nightly Emulator build](https://github.com/microsoft/botframework-emulator-nightlies/releases).

**Comment by mouhannadali** [comment]
Thanks, it is working now :)
