### ISSUE TITLE
issue with emulator

### ISSUE THREAD

**Issue by sailav** [Microsoft/BotFramework-Emulator#190]
404 [conversationUpdate]  

This is the issue I'm facing with I have already tried many but didnot find any result to overcome this

**Comment by eanders-MS** [comment]
Hi @sailav, What was the endpoint you specified in the emulator? A typical localhost endpoint looks like: `http://localhost:3978/api/messages`. I've seen 404s returned when the path part of the bot endpoint is in some way incorrect. For example, if you only specified `http://localhost:3978`, the bot would return a 404.

**Comment by eanders-MS** [comment]
Going ahead and closing this now. If you'd like further assistance, reply here and we'll reopen it.

**Comment by deepru2608** [comment]
@eanders-MS 

[20:19:58]Emulator listening on http://localhost:36873
[20:19:59]Failed to spawn ngrokspawn UNKNOWN
[20:19:59]
[20:19:59]POST401directline.conversationUpdate
[20:19:59]
[20:19:59]POST401directline.conversationUpdate
[20:19:59]POST201directline.startConversation
[20:20:04]-> messagehi
[20:20:04]Cannot post activity. Unauthorized.
[20:20:04]POST401directline.postActivity


I also getting these error, I don['t know why.....

**Comment by sailav** [comment]
Either it should be ngrok settings issue or something you written in you
both backend

**Comment by tonyanziano** [comment]
@deepru2608 Regarding the ngrok issue, do you have the path to the ngrok executable configured in your emulator app settings?

![image](https://user-images.githubusercontent.com/3452012/62883349-b5cc2400-bce8-11e9-95f4-0b1b526fa46a.png)

Also, I can see that you are getting a 401 error at the start of the conversation. This usually means that when you connected to the bot, you did not enter the correct credentials in the Microsoft App ID & Microsoft App Password fields.

![image](https://user-images.githubusercontent.com/3452012/62883486-03e12780-bce9-11e9-84cb-c201133ecb18.png)

What you enter into these input fields must match the credentials in your bot code.

===

Also, please don't mention `eanders-MS` because he no longer maintains this project.

**Comment by deepru2608** [comment]
@tonyanziano 

Thanks you so much for your help.
ngrok path is missing so i am getting that kind pf error.
and the reason of 401 error is bot emulator problem. i have update my bot than it's good to go.
and one more thing i am not using any kind of credential because i haven't deploy my bot.
