### ISSUE TITLE
Old SDK version warning message persists even after update

### ISSUE THREAD

**Issue by greuze** [Microsoft/BotFramework-Emulator#194]
With SDK versions 3.7.x and 3.8.x, the emulator is still showing warning messages:

>     Warning: The Bot is using an SDK version earlier than 3.5.0.
>     Warning: SDK versions earlier than 3.5.0 use an authentication configuration that will no longer work after July 31, 2017.
>     Warning: For your bot to continue working beyond this date, please update your bot to use an SDK version greater than or equal to 3.5.0.

Using `botframework-emulator v3.5.29`.

Question on [Stack Overflow](http://stackoverflow.com/questions/43931008/microsoft-bot-older-version-warning-message-persistent-even-after-update)

**Comment by eanders-MS** [comment]
Hi @greuze, The BotBuilder SDK reports its version number in the `User-Agent` header of the messages it sends to the emulator. Old versions of the Node SDK did not send this header, and so the emulator treats messages without it as coming from and "old" version of the SDK. Well, it turns out there's a small bug in the Node SDK where it still doesn't send this header in some localhost scenarios, causing the emulator to show the message you're getting.

We're going to patch the Node SDK to fix this issue, and also update the emulator with more accurate messaging, treating the SDK version as "unknown" version rather than "old".

@Stevenic, @Jeffders for tracking

**Comment by stevengum97** [comment]
@greuze & @eanders-MS,
@Stevenic released a fix for it today in version 3.8.3; if you're still running into issues please let us know by pinging one of us in [this](https://github.com/Microsoft/BotBuilder/issues/2775) BotBuilder issue. 

@greuze, I've also answered your question on [Stack Overflow](http://stackoverflow.com/questions/43931008/microsoft-bot-older-version-warning-message-persistent-even-after-update) so that others may find info there.
