### ISSUE TITLE
Inspecting LUIS Traces gives you an Access Denied error

### ISSUE THREAD

**Issue by jbeltranluna** [microsoft/BotFramework-Emulator#1967]
## Version
4.6.0.

## Describe the bug
Clicking on LUIS Traces in the emulator returns a new trace with the following message:
[LUIS] Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
The bot works perfectly even after the error shows up

## To Reproduce
1. Set up a bot with LUIS (LUIS App migrated to Azure Resources)
2. Test your bot locally with Emulator
3. Click on LUIS Trace to inspect the trace (everything is correct at this point, it even shows the correct information from the endpoint)
4. After 2 or 3 seconds, a new trace shows up on the Emulator Console showing the error message in red.
5. Bot works normally even after the error shows up.

## Expected behavior
Emulator shouldn't show that error I guess

## Screenshots
![image](https://user-images.githubusercontent.com/32138774/68213268-8709d500-ffdb-11e9-88ed-6bfcb647ff14.png)

## Additional context

[bug]

**Comment by tonyanziano** [comment]
Hi @jbeltranluna ,

Are you currently opening your bot via a `.bot` file, or are you connecting to the `localhost:3978` endpoint via URL only?

The LUIS inspector currently does not support bots opened via URL, because it requires the corresponding LUIS credentials to work properly:
  - region, subscription key, authoring key, app ID, and app name 

These credentials are stored in a `.bot` file, but are not associated to a bot when opened solely via the messaging endpoint.

**Comment by jbeltranluna** [comment]
Thank you @tonyanziano 

We are not using bot files since what I last read was that you were moving away from using those files (https://stackoverflow.com/questions/55473167/azure-bot-services-templates-botfilepath-botfilesecret-fields-are-missing-n)

Besides, when we worked with bot files we used a BotFileSecret that we now do not have it in the App Settings with the new Basic Template.

If the issue is strictly related to the bot file, you can close it since I only asked in case the LUIS credentials we were using weren't the right ones. 
Thank you :)
