### ISSUE TITLE
Add ability to customize behavior of Action.Submit in adaptive cards

### ISSUE THREAD

**Issue by fabio-muramatsu** [microsoft/BotFramework-Emulator#1980]
**Is your feature request related to a problem? Please describe.**
I'm using the bot framework and adaptive dialogs to write a MS Teams bot, and the bot emulator is a handy tool to debug and test the code locally. In Teams, we have the ability to customize the behavior of Action.Submit to set the `text` property sent to the bot, as described [here](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#adaptive-cards-actions). However, I couldn't find a way of getting the emulator to behave in a similar way - it will always submit the raw payload from `data` to the bot, and not set the `text` field. This makes it necessary to write custom code to handle a card response coming from Teams and one coming from the emulator, especially because the text field impacts intent resolution.

**Describe the solution you'd like**
I'd love if the emulator had a similar option to customize the behavior of Action.Submit like MS Teams does. Something like this would be nice:
```
{
  "type": "Action.Submit",
  "title": "Click me for messageBack",
  "data": {
    "msteams": {
        "type": "messageBack",
        "displayText": "I clicked this button",
        "text": "text to bots",
        "value": "{\"bfKey\": \"bfVal\", \"conflictKey\": \"from value\"}"
    },
    "botemulator": {
        "type": "messageBack",
        "displayText": "I clicked this button",
        "text": "text to bots",
        "value": "{\"bfKey\": \"bfVal\", \"conflictKey\": \"from value\"}"
    }
  }
}
```
Another possibility would be to set the emulator to emulate the MS Teams behavior, using whatever values we specify in the Teams field.

**Alternate solution**
As a workaround, I'm using a middleware to fetch the fields in `msteams` and replicate the behavior for the emulator.

[enhancement]

**Comment by mdrichardson** [comment]
@fabio-muramatsu I'd say this is less of an Emulator issue and more of a Botframework SDK issue. Teams just happens to handle this differently than all other channels.

You can set the `text` field from any channel by making the `data` field of the Adaptive Card a string, instead of an object. [See the "Submit Actions" heading of this blog post (about half way down)](https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/) for more info.

You'll also likely benefit from the links I posted in [this StackOverflow answer](https://stackoverflow.com/a/58629750/10860086). It looks like you're doing something similar to my recommendations in your middleware.

I know this isn't *quite* the answer you're looking for. Although I can't speak on behalf of Emulator/WebChat/Directline teams, I don't imagine this is something we'll implement on the Channel-level since Teams is the only one that does this, currently.

Should we close this issue, or is there still something that needs to be addressed?

**Comment by fabio-muramatsu** [comment]
Hm, I didn't know that Teams was the only one implementing this custom behavior. I'll probably keep my middleware, then. Thanks!
