### ISSUE TITLE
OnMembersRemoved event is not supported

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/BotFramework-Emulator#2027]
How do I simulate user leaving conversation?

**Comment by v-kydela** [comment]
Hi @turbozapekanka 

To answer your question, you can send activities to your bot in an Emulator conversation using the [Direct Line API](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference).

## Step 1: In Emulator

Make a note of the first two addresses that appear in the log panel, and pick one of them to use as the host for your Direct Line API calls (they both worked for me, so I'm not sure what differences you might encounter between them):

![image](https://user-images.githubusercontent.com/41968495/71487412-f4fa9d80-27cf-11ea-8277-c41469c11ed1.png)

Once the Emulator connects to a conversation with your bot, click on the "POST" button on this line:

```
[10:51:28] POST 200 directline.conversationUpdate
```

This will show you the channel account objects that you can put in your activity's JSON

![image](https://user-images.githubusercontent.com/41968495/71487541-caf5ab00-27d0-11ea-9bb0-edd3030fa379.png)

Now click on the "201" button on this line:

```
[10:51:28] POST 201 directline.startConversation
```

This will show you a conversation ID that you can use to form the path of your request. You will also see a token like "2" but the token isn't actually necessary because you can make unauthenticated requests to the Emulator's endpoint.

## Step 2: In Postman

Make a POST request to this endpoint:

```
<YOUR_HOST>/v3/directline/conversations/<YOUR_CONVERSATION_ID>/activities
```

The JSON body should look something like this:

```json
{
  "type": "conversationUpdate",
  "membersRemoved": [
    {
      "id": "ec4ed115-68cc-472e-ae03-08c32f8f6fab"
    }
  ]
}
```

---

Does this answer your question? I'm going to unassign myself from this issue so the team will see it in case you meant this as a feature request rather than a how-to question.

**Comment by turbozapekanka** [comment]
Yes this answers my question, thanks!
