### ISSUE TITLE
resend previous message with one click

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Emulator#2075]
### Use this [query](https://github.com/Microsoft/botframework-emulator/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when resending previous message.

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/2876650/73719447-71cb5080-475a-11ea-8f3f-c121f7505bc5.png)
Add `send again` in the context menu.

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by tonyanziano** [comment]
Hi @xieofxie ,

Just for clarification, the feature that you are asking for is a new context menu item to resend the selected activity back to the bot?

So for example, if the user sent messages A, B, and C to the Bot, he or she would be able to right click on message B, and resend it to the bot so that the conversation transcript would now read:

A, B, C, and D?

===

Also, what sort of scenario(s) do you find yourself in where this feature would be useful?

**Comment by xieofxie** [comment]
@tonyanziano You are right. It is actually 'Copy text' + paste in message box and enter.

When I debugging a bot, I often need to stop, fix the bot and rerun certain logic.

**Comment by tonyanziano** [comment]
Thanks for the feedback! @xieofxie

**Comment by cwhitten** [comment]
addressed with https://github.com/microsoft/BotFramework-Emulator/issues/2039
