### ISSUE TITLE
Custom/configured user ID is lost after restarting conversation

### ISSUE THREAD

**Issue by dmvtech** [microsoft/BotFramework-Emulator#2078]
## Version
4.7.0

## Describe the bug
When you set a custom user ID in the Emulator settings, it will work initially (after an emulator start). But as soon as you restart the _conversation_, it will be set to a new ID (GUID).

## To Reproduce
1. Set a custom ID in the Emulator settings
2. Talk to bot (ideally something that echo's the user ID)
3. Restart conversation. 
4. Talk to bot and see new ID/GUID
5. Restart emulator, talk to bot and see that user ID is properly using configured user ID.

## Expected behavior
Should still use custom/configured user ID after conversation update.

[bug]

**Comment by tonyanziano** [comment]
This is by design.

The "Restart Conversation" button has two options:

- restart conversation with new user ID (this is the default) -- will replace whatever your previous ID was with a fresh GUID
- restart conversation with same user ID -- this will preserve your previous ID and carry it into the new conversation

You can access the second option through the dropdown:

![image](https://user-images.githubusercontent.com/3452012/74410370-c2dbe400-4ded-11ea-86c1-ce2724e4e50d.png)
