### ISSUE TITLE
Allow to do Teams environment emulation and self-hosted bot using the Bot Emulator

### ISSUE THREAD

**Issue by SiarheiKuchukBelitsoft** [microsoft/BotFramework-Emulator#2117]
Hello

Upon development of a Bot for Teams i need to check it. But checking through build is not a good option. Therefore I'd like to have bot and light version of teams inside Bot Emulator so i can like login and do some testing

**Comment by tonyanziano** [comment]
Hi @SiarheiKuchukBelitsoft ,

We have no plans to emulate other channel behavior (such as Teams, Skype, etc.) inside the Emulator. Please see my comment in #2116 

The Emulator does have the ability to listen in on traffic to your bot through the Teams channel and display the traffic within the Emulator UI as it is now. In order to try that out, please check out the in-app Bot Inspector documentation:

![image](https://user-images.githubusercontent.com/3452012/77088984-770af480-69c2-11ea-94ed-7471560c4719.png)

**Comment by dmvtech** [comment]
@SiarheiKuchukBelitsoft You can also use [NGROK ](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/)to debug locally when using the Teams channel (in case you were not aware). You can also use Service Bus in place of NGROK. Let me know if want directions on how to do that.
