### ISSUE TITLE
“Bot Framework Emulator” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by jithinputhiyattu** [microsoft/BotFramework-Emulator#2120]
## Version
4.8.1

## Description

“Bot Framework Emulator” can’t be opened because Apple cannot check it for malicious software.
macOs (10.15.3) is showing this error dialog while opening the Emulator

## Screenshots
<img width="420" alt="Screenshot 2020-03-27 at 2 47 37 PM" src="https://user-images.githubusercontent.com/8542922/77741207-86311880-703a-11ea-871b-b3a41f0eedc9.png">

## Useful Link

https://stackoverflow.com/questions/59149730/heroku-pkg-can-t-be-opened-because-apple-cannot-check-it-for-malicious-softwar

**Comment by tonyanziano** [comment]
Hi @jithinputhiyattu ,

Thanks for the report!

It seems like since Mac OSX Catalina (10.15.x), applications must now be notarized by Apple as well in order to be completely whitelisted by Apple and not show this dialog. [(Source)](https://stackoverflow.com/a/58458252)

We are currently working on adding this notarization step into our release pipeline so that Mac Users no longer see this system dialog when launching the Emulator.

We will leave this issue open until this task is completed, and will update the issue accordingly.

**Comment by cleemullins** [comment]
This has been added to our R9 milestone, planned to ship in mid May.

**Comment by gourav1995** [comment]
Is this issue resolved already ?

**Comment by tonyanziano** [comment]
Hi @gourav1995 ,

No, this issue has not been resolved yet.

**Comment by gustavoalv** [comment]
So it mean I can not work with Bot Emulator on Mac?

**Comment by srinaath** [comment]
@gustavoalv We can work with Bot Emulator on Mac. It just has to be tagged as safe to open in the "Security and Privacy" section like this. The first time you open Emulator it would have queued up this warning in the Privacy section. Once marked safe you can continue using and you wont be prompted in the future.

![SecurityAndPrivacy](https://user-images.githubusercontent.com/13004779/79610913-4c3dba00-80ae-11ea-93bc-65e93c7ef790.png)
