### ISSUE TITLE
Command line switch - Silent install for all users

### ISSUE THREAD

**Issue by clue2** [microsoft/BotFramework-Emulator#2132]
Deploying Bot Framework Emulator using the command line install switch /S installs silently to a users profile.
Running the installer manually allows an option to install for all users (to Program Files X86), and set the install location.
It would be good if you could choose a silent install for all users via a command line switch.

**Comment by tonyanziano** [comment]
Hi @clue2 ,

Just to clarify:

- You are saying that running the `BotFramework-Emulator-windows-setup.exe` from the command line with the added switch `/S` will silently install the Emulator for the current user
- You would like the ability to add a second switch that would silently install the Emulator but for all users on the user's machine

**Comment by clue2** [comment]
Hi @tonyanziano ,

That is correct

**Comment by tonyanziano** [comment]
Hey @clue2 ,

This is not something we plan to fix, because we don't create or modify the NSH installer script that is run when you install the Emulator on Windows. It is actually the default script included by the [external packaging tool we use called Electron Builder.](https://www.electron.build/)

However, that being said, I dug around in some of the electron-builder NSIS installer source / documentation and it looks like you might be able to accomplish what you want by passing the `/allusers` switch to the installer.

I hope that works for you.
