### ISSUE TITLE
Input Field not showing on Emulator

### ISSUE THREAD

**Issue by michaeldera** [microsoft/BotFramework-Emulator#2158]
## Version
4.9.0

## Describe the bug
The emulator does not show an input dialog to send the response to the bot. 

## To Reproduce
Steps to reproduce the behavior: (This happens in debug mode)
1. I downloaded the Emulator on the releases page of this repository
2. Was prompted to update the Emulator and updated it. 
3. Add the local ngrok settings and enabled Authentication.
4. Started debugging a Visual Studio Core Bot template project after adding LUIS configuration. 
5. See error

## Expected behavior
I expected to see the input filed or an error/information message  with instructions
![image](https://user-images.githubusercontent.com/12817839/85210144-cce29600-b33d-11ea-9cbf-9cae428ad1c6.png)

## Additional context
Using Visual Studio 2019 on Windows 10 for debugging. 
![image](https://user-images.githubusercontent.com/12817839/85210126-960c8000-b33d-11ea-9224-10665a571f31.png)

[bug]

**Comment by tonyanziano** [comment]
Hi @michaeldera ,

This is by design and not a bug.

It looks like in the second screenshot with the missing input field, you have checked the "Open in debug mode" option in the Open Bot dialog.

![image](https://user-images.githubusercontent.com/3452012/85310924-796d6680-b469-11ea-9e7a-37f9a0ca241f.png)

If you check this option when connecting to a bot, the Emulator no longer acts as the client through which the user sends messages to the bot, but instead acts as a proxy that intercepts traffic between bot and user, and displays trace activities configured in the bot's Inspection Middleware. In this scenario, we hide the input field so that you cannot interact with the user through the Emulator.

If you want to interact with the bot through the Emulator using an input field, then do not check the "Open in debug mode" option.

**Comment by michaeldera** [comment]
Alright thank you. That clears it up
