### ISSUE TITLE
Be able to send arbitrary event/invoke with a JSON Payload

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Emulator#2174]
# Problem
There is no way to send arbitrary events or invoke using the emulator.  We need to support these to enable transcript-based testing as well as to allow triggering custom events.  One issue is that some events might need to be before or instead of the event sent on restart conversation.  For example, SetTestOptions event sets a random seed and that needs to have the conversation id sent by updateConversation but also need to be before it so the bot response to updateConversation is not random.

# Solution
Please add to the Conversation send activity menu a way to send an event or invoke with an arbitrary JSON payload.  

[enhancement]

**Comment by joe-tossell-mando** [comment]
I have had exactly this problem recently when trying to emulate the webchat/join event specified in the microsoft documentation and referenced in this issue:
https://github.com/microsoft/BotFramework-WebChat/issues/2120#issuecomment-516056614

I've had to emulate using a razor page and a bot registration routing to an ngrok endpoint in order to reliably test this. We're using the webchat/join even to indicate the page the webchat is being activated on to provide a more contextual experience.

**Comment by tonyanziano** [comment]
This feature will be available in tonight's nightly build. Check out #2213 for details

**Comment by tonyanziano** [comment]
There is currently an issue with the nightly pipeline that we are working to fix. Stay tuned

**Comment by tonyanziano** [comment]
The latest nightly here includes this feature: https://github.com/microsoft/botframework-emulator-nightlies/releases/tag/v4.11.0-199884
