### ISSUE TITLE
Compliance Policy for Graph API Hindering Use of Emulator 

### ISSUE THREAD

**Issue by rprecioso** [microsoft/BotFramework-Emulator#2208]
## Version
Version 4.11.0

## Describe the bug
When Graph API Permission is enabled for Files.ReadAll, the company specific policy for sensitive data is hindering the SSO login to continue. The authentication does continue anymore because it doesn't treat the emulator as a proper browser. Regardless if I remove the API permission in the Azure App Registration, the issue does not resolve it. Internally, this could be resolved by using our company-specified browsers (Edge or IE) to continue with the consent. 

## To Reproduce
1. Enable AADv2 Authentication for your ChatBot App
2. Include Files.ReadAll (Delegated) in the API Permission and Scope
3. Launch ChatBot, continue with login
4. Next step should be about approving the consent, but this is where it is stuck

## Expected behavior
Consent should still continue

## Screenshots
![image](https://user-images.githubusercontent.com/47111908/100751912-e1fe3d80-3422-11eb-8077-7db277510d0f.png)

## Additional Info
I also posted in Stackoverflow but unfortunately I didn't find any help
https://stackoverflow.com/questions/64979954/bot-framework-emulator-authentication-compliance-policy-issue

[bug]

**Comment by tonyanziano** [comment]
Hi @rprecioso ,

This is due to a security policy change within certain Microsoft tenants.

We recently faced the same issue over in the [Bot Framework Composer](https://github.com/microsoft/BotFramework-Composer), and had to fix it by doing a complete overhaul of the way auth works and using a native Node library that actually leverages certain OS-level authentication & security APIs.

I assume we will have to do the same thing in Emulator in order to fix this, because we don't have any control over the browser that is embedded within Electron (Chrome).

Sadly, there is no work around for this.

This will require a lot of work, and we have yet to resource any work items for the upcoming release schedule, but I will make sure to add this to the list of outstanding issues to review when that planning session occurs.

I will update this issue accordingly once we have that planning session.

**Comment by tonyanziano** [comment]
If you are able to deploy your bot so that you can test it in a web context (outside of Electron), then it should work properly, however, I do not expect authentication within the Emulator to work currently.

Were you trying to sign in to an @microsoft.com account? Or do you happen to know if it was a personal / school account?

**Comment by rprecioso** [comment]
> Hi @rprecioso ,
> 
> This is due to a security policy change within certain Microsoft tenants.
> 
> We recently faced the same issue over in the [Bot Framework Composer](https://github.com/microsoft/BotFramework-Composer), and had to fix it by doing a complete overhaul of the way auth works and using a native Node library that actually leverages certain OS-level authentication & security APIs.
> 
> I assume we will have to do the same thing in Emulator in order to fix this, because we don't have any control over the browser that is embedded within Electron (Chrome).
> 
> Sadly, there is no work around for this.
> 
> This will require a lot of work, and we have yet to resource any work items for the upcoming release schedule, but I will make sure to add this to the list of outstanding issues to review when that planning session occurs.
> 
> I will update this issue accordingly once we have that planning session.

Thank you for this. I hope I can contribute on this as well.


> If you are able to deploy your bot so that you can test it in a web context (outside of Electron), then it should work properly, however, I do not expect authentication within the Emulator to work currently.
> 
> Were you trying to sign in to an @microsoft.com account? Or do you happen to know if it was a personal / school account?

It's an organization account that I am using in our company. Weird thing is, if I remove the scope in API permission  that is having an issue it doesn't resolve the issue. Would you know if it's cached somewhere?

**Comment by tonyanziano** [comment]
> It's an organization account that I am using in our company. Weird thing is, if I remove the scope in API permission that is having an issue it doesn't resolve the issue. Would you know if it's cached somewhere?

Do you mean that previously, if you tried to sign in without specifying a scope you were not getting this error?

As far as I know, it is not cached anywhere.

**Comment by taicchoumsft** [comment]
@rprecioso , do you have an update for @tonyanziano's question?

**Comment by gabog** [comment]
Hi @rprecioso, closing this one due to inactivity, feel free to reopen it if you need further assistance.
