### ISSUE TITLE
Activity not getting displayed on emulator

### ISSUE THREAD

**Issue by barnabaskim95** [microsoft/BotFramework-Emulator#2266]
Activity sent by bot service isn't showing up on emulator (4.12/ 4.13) on my machine. Am able to log into bot.

**Comment by anusharavindrar** [comment]
@barnabaskim95, can you elaborate more on what you are trying to do? If you can follow the below bug template and add all the details, it would be really helpful:


## Version
What version of the Emulator are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Additional context
Add any other context about the problem here.

[bug]

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to reopen if the issue persists.
