### ISSUE TITLE
Text output window size

### ISSUE THREAD

**Issue by maksoy20999** [microsoft/BotFramework-Emulator#2436]
## Version
What version of the Emulator are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]
How can I adjust the text output size after the bot displays the results?

**Comment by stevkan** [comment]
Unfortunately, Emulator doesn't allow changing any rendering characteristics. The size of any the text in any displayed responses is a fixed size, with the exception of rendered adaptive cards.

If this is still an issue to you and it is important, you have a few alternatives. One, you could clone and build the project locally so you can make any desired changes. Two, you could use [BotFramework-WebChat](https://github.com/microsoft/botframework-webchat) as your client which would allow you to adjust the HTML. This latter option provides a similar experience to Emulator since Emulator relies on Web Chat, internally, for the client.
