### ISSUE TITLE
How can I use the microphone button at bottom right

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/BotFramework-Emulator#252]
How can I use the microphone button at emulator and send a voice message? Is there an example of directly sending voice at conversation? I want to use with speech to text and LUIS. Thank you!

**Comment by eanders-MS** [comment]
I think this blog post describes the process: https://blog.botframework.com/2017/06/26/Speech-To-Text

**Comment by YanXuHappygela** [comment]
Thank you. But do I have to register my bot to test this out? Or I can simulate this locally at emulator?

**Comment by eanders-MS** [comment]
No need to register your bot with the bot framework to use the speech services.

**Comment by YanXuHappygela** [comment]
Thank you. i have tried to simulate this demo at emulator but it never allows me to input voice or read out the text. Is there any other step I'm missing? To have the communication by voice without registering it as Cortana skill?
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/demo-RollerSkill

**Comment by EricDahlvang** [comment]
Hi @YanXuHappygela 

Please try registering your bot on the dev portal, and adding the MicrosoftAppId & MicrosoftAppPassword to the bot's .env ( https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/demo-RollerSkill/.env ) and to the emulator.  

This line: https://github.com/Microsoft/BotFramework-Emulator/blob/c014d0494cd4eaefa5e1b7d1fd6e745c1c2ad504/src/server/conversationManager.ts#L451 in the emulator's code states: 'To use speech, the bot must be registered and using a valid MS AppId and Password.'  I'm not sure how to use speech in the emulator otherwise.

I hope this helps.  Please let us know how it goes.

**Comment by YanXuHappygela** [comment]
I have created a MicrosoftAppId and password and created a bot service with this. With this AppId and password, I can use the speech function now! Thank you for your help! I'm curious to know how the app knows that the app will use the speech API? Or it will just use that by default once I have turned on speech to text cognitive service? Thanks a lot!

**Comment by eanders-MS** [comment]
Thanks @EricDahlvang. Closing this issue now.
