### ISSUE TITLE
Emulator try to connect through authentication proxy server to localhost

### ISSUE THREAD

**Issue by joe90mizuno** [Microsoft/BotFramework-Emulator#345]
![image](https://user-images.githubusercontent.com/24535080/32823467-b15233b8-ca20-11e7-970f-b6aed85d487f.png)

.67 : my pc, .135 : pac file server, .88 : authentication proxy server

When I push connect button on emulator, emulator read proxy pac file from 135 sever at first. 
Pac file is good, so emulator should connect DIRECT to localhost. 
But emulator try to connect through proxy server to localhost.

**Comment by eanders-MS** [comment]
This issue is difficult because we're not able to repro locally, but I wonder if we can provide additional levers that allow you to control how and when the emulator utilizes your proxy. We could start by adding a command line parameter to disable reading of proxy settings.

This is our most intractable issue. I appreciate your persistence.

**Comment by cwhitten** [comment]
@joe90mizuno are you still seeing this issue on the latest version of the Emulator? (v4.2.1)

**Comment by cwhitten** [comment]
Closing, stale.
