### ISSUE TITLE
emulator doesn't support some of the style in prompt dialog like promptstyle.inline,keyboard .

### ISSUE THREAD

**Issue by SaranrajK** [Microsoft/BotFramework-Emulator#346]

**Comment by FranciscoPonceGomez** [comment]
Hi @SaranrajK,

Do you get any errors or is just that the dialog doesn't render they way you would expect in the emulator?

-Francisco

**Comment by SaranrajK** [comment]
Hi @FranciscoPonceGomez,
I didn't get any errors when prompt style.Inline, it has to show options in the same line, it shows them in the same line but not as options it shows them as plain text.

**Comment by eanders-MS** [comment]
This sounds to me like a problem with the webchat control, rather than the emulator itself. The distinction isn't clear from the user perspective, but the emulator consumes the webchat control as an npm package. It has its own repo here: https://github.com/Microsoft/BotFramework-WebChat/

If you can post the json of the message containing the misformatted prompt, I will check it against the webchat control.

**Comment by cwhitten** [comment]
Closed as a WebChat issue and lack of activity.
