### ISSUE TITLE
[Feature Request] State Data - Local Visualization

### ISSUE THREAD

**Issue by matthewshim-ms** [Microsoft/BotFramework-Emulator#353]
I think we have some potential to add a useful feature to the emulator to visualize conversation state data. This will help bot production by enabling users to preview state data while prototyping, before pushing to production. 

Since we're strongly encouraging bot developers to manage their own state data, this will help by providing new bot developers with a way to visualize that data and understand what it is. Currently, many new users are not aware of the default state service at all.

**Comment by eanders-MS** [comment]
Cool idea @matthewshim-ms, thanks!

Just thinking out loud how this might look: A state viewer could be integrated into the app pretty naturally as second tab on the Details pane. Getting it to work would require changes in the SDK, so that bots talking to the emulator will store state using the emulator's state store. It would be a debug setting in the SDK to enable this.

**Comment by tonyanziano** [comment]
This is being accomplished in #1394
