### ISSUE TITLE
Modal dialogs do not prevent outside tab key navigation

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-Emulator#360]
When a modal dialog is visible, it should limit tab key navigation to within the dialog. Also, we need a dialog manager class.

**Comment by compulim** [comment]
Few ideas when componentizing out the dialog box component:
* For the focus trap, see if you can automatically find the first focusable element using part of the code from [here](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/getTabIndex.ts). Reasons for the code can be found [here](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/getTabIndex.ts), mainly because `tabindex` is wrong in browsers make it difficult to detect focusable element
* Add <kbd>ESC</kbd> to close the dialog

**Comment by eanders-MS** [comment]
Fixed by https://github.com/Microsoft/BotFramework-Emulator/pull/365. Thank you @corinagum !
