### ISSUE TITLE
Unable to connect local bot to Bot Framework Channel Emulator

### ISSUE THREAD

**Issue by CNapo** [Microsoft/BotFramework-Emulator#401]
I  run the [LUIS Bot Sample application.](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/intelligence-LUIS) I can open the url in browser http://localhost:3979/api/messages/, but got error message as below.
```
<Error>
<Message>
The requested resource does not support http method 'GET'.
</Message>
</Error>
```
**I installed the latest version this morning but I cannot connect to localhost bots.**

![image](https://user-images.githubusercontent.com/13250007/35036114-3b8821e6-fbae-11e7-9a3f-be7c5ed8ceba.png)

**Comment by EricDahlvang** [comment]
Hello @CNapo 

Is there any helpful information displayed in the **Details** window if you click on one of the **301** links in the **Log** window?

**Comment by CNapo** [comment]
Hello Eric
FYI, I need to use the corp proxy server (.pac) for internet access. 
![image](https://user-images.githubusercontent.com/13250007/35077034-2a2de5ba-fc36-11e7-9760-32e6f8f8bb0a.png)

**Comment by EricDahlvang** [comment]
I'm sorry you're running into this issue.  The emulator's current implementation doesn't handle a proxy setup as well as it could.  We have a fix planned for this described here: https://github.com/Microsoft/BotFramework-Emulator/issues/363 This is one of the highest priority issues in our backlog.  We appreciate your patience.

In the mean time, here are a couple suggestions to try that might unblock you (depending upon your setup):

- Change the path to http://127.0.0.1/api/messages
- Use https instead of http

**Comment by CNapo** [comment]
unfortunately, both 127.0.0.1 and https do not work for me. I got "Invalid Hostname" for 127.0.0.1 and "tunneling socket could not be established, statusCode=503 " for https

**Comment by cwhitten** [comment]
Closing, stale.
