### ISSUE TITLE
Connecting to BotFramework-Emulator using DirectLine .NuGet package causes exception

### ISSUE THREAD

**Issue by jamesmundy** [Microsoft/BotFramework-Emulator#407]
I'm currently using v3.5.35 of the BotFramework-Emulator and speaking to it using the [DirectLine .NET NuGet package](https://www.nuget.org/packages/Microsoft.Bot.Connector.DirectLine). Both use v3 of the DirectLine API but some methods in the library are not compatible with this version of the emulator.
For example:
When it comes to reconnecting to a channel using:
`var conversation = await client.Conversations.ReconnectToConversationAsync("fi7156l5cmce");`

I get the following JsonSerializationException:
```
{"Input string '1.7976931348623157e+308' is not a valid integer. Path 'expires_in', line 1, position 92."}
{\"conversationId\":\"fi7156l5cmce\",\"token\":\"fi7156l5cmce\",\"expires_in\":1.7976931348623157e+308,\"streamUrl\":\"\"}"
```

It seems that perhaps a variable has changed in the implementation of the DirectLine API in the emulator but not in the NuGet library which hasn't been updated for 9 months. Is this a known issue? And which implementation is the correct one?

**Comment by EricDahlvang** [comment]
Hi @jamesmundy 

Thank you for bringing this to our attention.   Turns out the Emulator is setting expires_in using Number.MAX_VALUE (1.7976931348623157e+308) on line 125 of conversationsControllerV3.ts 
https://github.com/Microsoft/BotFramework-Emulator/blob/c014d0494cd4eaefa5e1b7d1fd6e745c1c2ad504/src/server/controllers/directLine/conversationsControllerV3.ts#L125 (also line 107)

The Conversation.ExpiresIn property in Microsoft.Bot.Connector.DirectLine is a nullable int (max value: 2147483647).

We will get this fixed in the next release.
