### ISSUE TITLE
Emulator not handling screen DPI after Windows April 18 Update

### ISSUE THREAD

**Issue by paulio** [Microsoft/BotFramework-Emulator#461]
The text is now tiny and unreadable

**Comment by EricDahlvang** [comment]
Please try zooming with ctrl++ to zoom out and ctrl+- to zoom in

![emulatorzoom](https://user-images.githubusercontent.com/11055362/39715850-6d1787c0-51e3-11e8-9310-7aff1c167de3.gif)

**Comment by eanders-MS** [comment]
On this topic we're subject to the behavior of the [Electron app framework](https://electronjs.org/). You might try perusing their issues page for a solution or workaround.

**Comment by paulio** [comment]
@EricDahlvang yes the zooming thing is what I've had to do but obviously it's not an ideal experience. @eanders-MS whilst I appreciate it's tricky it's still a problem with the bot-framework that the bot-framework team might want to take up with Electron.

**Comment by tonyanziano** [comment]
I'm on version 10.0.17763 Build 17763 of Windows and the Emulator seems to respect whatever DPI setting your display is set to. 

For example, on my 4k monitor, if I set the scale of the display to the default of 100% instead of the recommended 150%, the emulator and all other applications become smaller. This behavior seems correct to me, and I don't think that the emulator should be expected to remain a static size whenever the scale of the display is changed.
