### ISSUE TITLE
Bot Framework V4 Quicker Connect + Endpoint suggesting

### ISSUE THREAD

**Issue by thebillkidy** [Microsoft/BotFramework-Emulator#609]
Hi All,

First of all, loving the new UI! looks slick and clean and allows for multiple bot configurations - which I love a lot :)

I am however missing a couple of things that I would maybe like to see added if possible?

* **Instant connection:** In the old Bot Framework Emulator we could just click the blue bar, and http://localhost:3978/api/messages would automatically pop up, allowing us to connect instantly for development.
* **Suggestion for the correct endpoint?** When I start the bot, it doesn't fill in anything for me. Could we maybe add a *placeholder* field showing http://localhost:3978/api/messages as default endpoint? :)

**Comment by mewa1024** [comment]
Thanks for this feedback. This is an interesting counterpoint to the behavior we saw from new users in usability studies: with the endpoint field prefilled, users didn't pay any attention to the endpoint URL and therefore didn't realized they needed to change it when using a sample bot that used a different endpoint. Because of that we chose to remove the default endpoint. But we'll keep this in mind while we're refining the UX.

**Comment by vishwacsena** [comment]
@thebillkidy - we've made considerable investments on both these pieces of feedback in the latest emulator release - 
1 - you can now very easily create a new bot configuration and connect to your bot. You can also easily open saved bot configurations via the MRU list in the Welcome page as well as via File -> open menu.
2. We've also added hint text for /api/messages in the new bot configuration dialog. 

Marking this as closed. Please feel free to reactivate or file a new ticket with other suggestions you may have. 

Thank you!
