### ISSUE TITLE
Text to speech doesn't work and no errors showed.

### ISSUE THREAD

**Issue by meksikann** [Microsoft/BotFramework-Emulator#634]
Hi. No any sound made from bot when it responds.

I am testing bot on localhost with botEmulator.
OS: Linux Ubuntu
 "name": "botframework-emulator",
  "version": "3.5.35",

Used valid  MS App ID and MS APP password in BotEmulator and Bot app.

Bot code:

```js
bot.dialog(intents.Greeting, function (session) {
  const userName = session.message.user.name;
  var msg = new builder.Message(session)
    .speak('This is the text that will be spoken.')
    .inputHint(builder.InputHint.acceptingInput);
  session.send(msg).endDialog();
})
  .triggerAction({
    matches: intents.Greeting
});
```

Bot responds on greeting.. and response JSON is: 

```json
{
  "type": "message",
  "speak": "This is the text that will be spoken.",
  "inputHint": "acceptingInput",
  "locale": "en-US",
  "localTimestamp": "2018-06-07T14:17:34+03:00",
  "from": {
    "id": "default-bot",
    "name": "Bot"
  },
  "recipient": {
    "id": "default-user"
  },
  "id": "someID",
  "replyToId": "someID",
  "channelId": "emulator",
  "timestamp": "2018-06-07T11:17:34.570Z",
  "conversation": {
    "id": "someotherID"
  }
}
```

No any errors in logs. Just this:

```bash
[14:11:18] Emulator listening on http://[::]:44979 
[14:11:18] ngrok not configured (only needed when connecting to remotely hosted bots) 
[14:11:18] Connecting to bots hosted remotely 
[14:11:18] Edit ngrok settings 
[14:17:31] -> POST 202 [conversationUpdate] 
[14:17:31] -> POST 202 [conversationUpdate] 
[14:17:33] -> POST 202 [message] hello 
[14:17:34] <- POST 200 Reply[message] 
[14:17:34] <- POST 200 Reply[event] Debug Event  `
```

I've read all issues cases on Git, but still cannot hear any sound from the bot.
Will be greatfull for help.Maybe I do something wrong but it's hard to see from my side:)

**Comment by stevengum97** [comment]
Cross linking duplicate Stack Overflow question: https://stackoverflow.com/questions/50740112/text-to-speech-doesnt-work-and-no-errors-showed-in-botemulator

**Comment by meksikann** [comment]
removed from stackoverflow

**Comment by stevengum** [comment]
@meksikann sorry for the delay, can you confirm which version of Ubuntu are you using?

**Comment by meksikann** [comment]
@stevengum hi. it's Ubuntu 16.04 LTS

**Comment by stevengum** [comment]
@meksikann sorry for the delay, I'll try to get a repro on this tomorrow or the day after.

**Comment by cwhitten** [comment]
@stevengum any updates here? :)

**Comment by corinagum** [comment]
@meksikann Sorry for the delay in getting back to you.
Bing Speech underwent a big [API update](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-migrate-from-bing-speech) to Speech Services back at this year's Ignite. Because of this, Bing Speech no longer allows the creation of new speech bots, and Bing Speech will be deprecated in 10/2019. 

Our plan is to have **Speech Services** supported (through the latest Web Chat) on Emulator very soon, and that progress can be tracked [here](https://github.com/Microsoft/BotFramework-Emulator/issues/1206). 

This update would mean that bots using Speech Services can support speech. At the moment there is no plan to back-support Bing Speech in Emulator or Web Chat. For more information on Web Chat supporting Speech Services, please take a look at https://github.com/Microsoft/BotFramework-WebChat/issues/1336.
