### ISSUE TITLE
When opening a transcript generated by chatdown, only messages from the bot are shown in the WC panel

### ISSUE THREAD

**Issue by tonyanziano** [Microsoft/BotFramework-Emulator#649]
Repro:

1. Take `.chat` file
2. Generate `.transcript` file using chatdown CLI or as a library
3. Open the generated `.transcript` file in the Emulator

---

@compulim and I debugged it and found that the cause is due to the generated activities from the user lacking the `channelData` & `channelData.clientActivityId` properties which then get filtered out by Webchat

(inside of `Store.js` --- `Receive_Sent_Message` action case)

---

Sample `.chat` file:

    user=Tony
    bot=TestBot
    
    user: Hello :)
    bot: Hey there Tony!
    user: How's it going today TestBot?
    bot: Awesome. How about you?
    user: Great.

**Comment by compulim** [comment]
And in the code, the `channelData.clientActivityId` check is:
* If there is `channelData.clientActivityId`, it means this is not a "postback message"
* Otherwise, it is a "postback" and we should not show the message

This logic feels weird to us. We need more time to dig into the documentation and see why it is there because it doesn't make too much sense for us in our current understanding.
