### ISSUE TITLE
bot code

### ISSUE THREAD

**Issue by HadasBrown** [Microsoft/BotFramework-Emulator#654]
Hi all! who can I ask about the code of the bot itself? right now my bot is working and replying an echo of what i said and how many characters it had. but i want my bot to **start** a conversation. how do i do that? i want the bot to say hello first regardless to a user input. the method "post async" only prints the message to the chat **after** input was received from the user.

any help? if not here then where to ask????
please!
thank you
Hadas

**Comment by JasonSowers** [comment]
@HadasBrown The correct place to ask how to questions is on stack overflow with the bot framework tag.  You can also reach out via the [SDK repository](https://github.com/Microsoft/BotBuilder/issues/new).  What you are looking for is called [proactive messages](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-proactive-messages?view=azure-bot-service-3.0).  Keep in mind the bot will only be able to send a proactive message if a user has interacted with the bot already.  This is intentional to prevent spambots.

[C# Sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-proactiveMessages)  
[Node Sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-proactiveMessages)
