### ISSUE TITLE
Bot not loading in bot framework emulator 

### ISSUE THREAD

**Issue by Fulljames1** [Microsoft/BotFramework-Emulator#684]
I am currently trying to run the C# basic bot with the bot framework emulator but every message I send results in a couldn't send, and the log remains empty.

This is what I have for the settings:
![capture1](https://user-images.githubusercontent.com/25401495/42629999-3958e208-85cd-11e8-8a15-0734653f4530.PNG)

This is my response when I run my bit in visual studio:
![capture](https://user-images.githubusercontent.com/25401495/42630020-4f0ced6a-85cd-11e8-9ba9-c81586699d2b.PNG)

An this is what is displayed in the bot framework emulator:
![capture2](https://user-images.githubusercontent.com/25401495/42630069-6becea66-85cd-11e8-8acc-9fd59b8aae3f.PNG)

Any help would be much appreciated!

**Comment by jwiley84** [comment]
The Bot Framework team prefers "How To" questions be asked on Stack Overflow. This Github repo is used primarily for bugs and feature requests. Addtionally, your question is in the process of being answered on Stack Overflow (https://stackoverflow.com/questions/51287242/cannot-connect-c-sharp-basic-bot-to-bot-framework-emulator). Please see additional comments that have been posted there and respond so that the support engineers can further assist you.

**Comment by justinwilaby** [comment]
Thanks for posting @Fulljames1  - 

For now, we're closing this in favor of Stack Overflow as the platform for questions. I'm confident you'll get the help you need there.
