### ISSUE TITLE
Emulator doesn't enable the user to select/enter authentication information when using oAuthPrompts

### ISSUE THREAD

**Issue by darrenj** [Microsoft/BotFramework-Emulator#768]
When using the Emulator to test a Bot that leverages oAuthPrompts it would appear the Emulator (and likely Chromium) is caching prior authentication across instances of the emulator and even reboots of the PC.

As the attached video shows, this means that when you click a sign-in link you get a popup window which would normally show authentication information (e.g. type email address) which quickly disappears having taken cached authentication from before and returns a token. In my case for my MSA not my domain credentials which are needed for my scenario.

You get similar behaviour with browsers/edge and InPrivate mode works well to work around this. We should perhaps look at removing cached state from Chromium after Emulator has closed or have a button somewhere to do this?

[Bot Framework Emulator (V4 PREVIEW) - CalendarSkill 2018-08-15 14-42-34.zip](https://github.com/Microsoft/BotFramework-Emulator/files/2290392/Bot.Framework.Emulator.V4.PREVIEW.-.CalendarSkill.2018-08-15.14-42-34.zip)

**Comment by justinwilaby** [comment]
@darrenj @sgellock  - With the completion of the AAD -> LUIS flows, we have a requirement to cache previous sessions when the user chooses "Keep me signed in". This means allowing electron to cache their session.  If the user does not wish to remain signed in, [this code](https://github.com/Microsoft/BotFramework-Emulator/blob/v4/packages/app/main/src/main.ts#L419) signs the user out when the emulator is closed and causes the user to be prompted for credentials on the next auth attempt.

Also, once the user is signed in, [they can sign out](https://github.com/Microsoft/BotFramework-Emulator/blob/c40db89e37a936f2110e75c0ee1d08e15f8475c7/packages/app/main/src/appMenuBuilder.ts#L192) using the file menu.

I believe this should address the issue you're seeing. Since this code was pushed yesterday, it might be a good idea to get you a fresh binary to begin banging on.

**Comment by sgellock** [comment]
@darrenj assumed resolved.  if not, please reopen.

**Comment by d0ggyRul3z** [comment]
hi there @sgellock , it appears to me that v4.0.41504 is not allowing OAuthPrompt to trigger.
Perhaps we can reopen this item?

**Comment by sgellock** [comment]
Yes.  Let’s do that.  Can you re-open the ticket please?
