### ISSUE TITLE
Emulator protocol launch to bot file does not work

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#804]
bfemulator://bot.open?path=${BOT_FILE}&endpoint=${server.url} does not work!

**Comment by justinwilaby** [comment]
@vishwacsena  - Do we have repro steps for this one? 
Was it launched from a website? On Chrome? Edge? Locally from OneNote?  Your auntie's Mac?

**Comment by tonyanziano** [comment]
@vishwacsena 

Ok, so I was able to get this working in my environment, but there was an initial issue that I came across that you might be running into.

So when you add your protocol parameters (`${BOT_FILE}` / `${server.url}` in your case), you need to make sure that they are URL encoded. One way this can be done is by opening your browser's dev tools, going into the console, and typing `encodeUriComponent(YOUR_VALUE)` to encode the value.

**Example:**

`encodeURIComponent('outerFolder/innerFolder/myBot/myBot.bot')` 

=> `"outerFolder%2FinnerFolder%2FmyBot%2FmyBot.bot"`

so then your protocol would look like:

`bfemulator://bot.open?path=outerFolder%2FinnerFolder%2FmyBot%2FmyBot.bot`

**However**, one issue I found while testing this was that URL encoding doesn't play nicely with Windows paths because of the `\` characters. The encoding thinks that the character immediately after the backslash is being escaped, and so then it encodes both the backslash and the following character instead of just the backslash, which produces a wrongly encoded string.

**Example showing incorrect en/decoding on windows path:**

`encodeURIComponent('some\path\to\a\file') => "somepath%09oa%0Cile"`

`decodeURIComponent("somepath%09oa%0Cile") => "somepath	oaile"`

In order to get around this, Windows paths need to have their backslashes converted to forward slashes before being encoded, and then it should work.

**Example showing above path en/decoded after converting to forward slashes:**

`encodeURIComponent('some/path/to/a/file') => "some%2Fpath%2Fto%2Fa%2Ffile"`

`decodeURIComponent("some%2Fpath%2Fto%2Fa%2Ffile") => "some/path/to/a/file"`

**Comment by tonyanziano** [comment]
De-prioritizing after today's standup discussion
