### ISSUE TITLE
Clicking on Bot Explorer to collapse panel resets webchat

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#825]
1. Open Emulator
2. Open a bot file
3. Talk to the bot 
4. Click on Bot Explorer to collapse the explorer panel

Expected: Webchat is not reset

Actual: Webchat is reset.

See attached video. 
[Media1.zip](https://github.com/Microsoft/BotFramework-Emulator/files/2350238/Media1.zip)

**Comment by vishwacsena** [comment]
promoting to p0.

**Comment by compulim** [comment]
@justinwilaby The reason why Web Chat is reset is because <MDI> of the Emulator app get reconstructed every time the panel is collapsed/expanded.

https://github.com/Microsoft/BotFramework-Emulator/blob/v4/packages/app/client/src/ui/shell/mdi/mdi.tsx#L55

If you put a breakpoint at the constructor of `<MDI>`, it will get hit every time the panel is collapsed/expanded. We need to make sure the `<MDI>` is not reconstructed because there is no modifications for the content of the panel.

Web Chat don't preserve the history/connection if it is unmounted/remounted, and currently there is no plan on working on this feature.

**Comment by tonyanziano** [comment]
So this ended up being a much tougher fix than I expected. I have a fix in my branch that works, but that I'm not entirely satisfied with. I would like to revisit this in the future and polish up the splitter-side logic so that it is more flexible.

**Comment by tonyanziano** [comment]
De-prioritizing due to workaround #910 

However this should still be fixed because the same issue happens when splitting an active livechat tab to a new tab group.
