### ISSUE TITLE
Emulator UI: navbar icons should lose focus after they are pressed

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Emulator#830]
Build 4.0.262-nightly

Click "Bot Explorer" icon top open/close pane. The blue bar stays present until you click on a different part of the app. The blue bar should appear when pressed and disappear when not pressed. Occurs in all themes.

![image](https://user-images.githubusercontent.com/39317542/45128969-b43bc880-b135-11e8-840f-97e88c76d2b8.png)

**Comment by justinwilaby** [comment]
`focus` events occur by default when any item is clicked. Overriding this default browser behavior is not trivial because:
1. `focus` events occur before click events which means a flash of the focused state on the button will occur before it is removed manually each time it is clicked.
2. Preventing the focused state flash would mean implementing additional logic to track `mousedown` events, switch a flag and then prevent focus using `event.preventDefault()` in the focus handler.

**Comment by OEvgeny** [comment]
Looks like it got fixed due accessibility updates. Now focus lands on the changed page UI
