### ISSUE TITLE
Encrypt keys stored in your bot configuration

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#872]
Two issues .. 
- this string could be updated to read 'Encrypt keys stored in your bot configuration file'
- The checkbox stays unchecked when I opened a bot file that is encrypted.

![image](https://user-images.githubusercontent.com/20918136/45569776-70bc1b00-b815-11e8-9129-f043cb570c9f.png)

**Comment by mewa1024** [comment]
@vishwacsena Do we need to make that text change? We use "bot configuration" in the UI of the "New bot configuration" flow: the text on the Welcome page, File  > New Bot Configuration, and the "New Bot Configuration" modal title. Is it confusing in this case not to specify that it's a file because encryption is involved?

**Comment by vishwacsena** [comment]
@mewa1024 sure. That makes sense

**Comment by mewa1024** [comment]
Updated the comp to show the change in wording from "Reset" to "Generate new key" and two make the key field shorter.

Encryption off: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/15183213/315673917/preview](url)
Encryption on: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/15183213/320119845/preview](url)

**Comment by tonyanziano** [comment]
Fixed in #916
