### ISSUE TITLE
Tabs should show the name of the endpoint or filename (for transcripts and scripts) instead of the generic "Transcript" or "Live Chat"

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#873]
When you open a transcript file in emulator, the tab title is set to 'Transcript' but this instead should show the chat or transcript file name

![image](https://user-images.githubusercontent.com/20918136/45569858-af51d580-b815-11e8-90b2-b122c82c73b2.png)

**Comment by mewa1024** [comment]
Agree. This should say the file name. Tabs should have a max width of 200px, at which the file name truncates with ellipses. Full document path should appear on hover.

**Comment by mewa1024** [comment]
Updated specs on Invision to illustrate the truncation behavior. 
Complete Emulator style guide is here: hhttps://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/14907902
Look in the "Tabs" section.

**Comment by mewa1024** [comment]
Changing the name of this issue from **"Transcript tabs should show the file name instead of the generic 'Transcript'"** to  **"Tabs should show the name of the endpoint (for conversations) or filename (for transcripts and scripts) instead of the generic "Transcript" or "Live Chat"**, since this effects transcripts, conversations, and script/.chats.
