### ISSUE TITLE
New bot configuration should automatically generate a key using bot configuration library

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#879]
File -> new bot configuration experience should match Bot settings with regard to encryption. 

When user selects 'encrypt keys', a key should be automatically generated using the bot configuration library w/ options for the user to copy the key. 

Also via #871  and #872 we should have the right set of afforances here for the user so they know they need to copy the key, update application settings etc. 

![screen shot 2018-09-14 at 12 37 57 pm](https://user-images.githubusercontent.com/20918136/45571441-0c9c5580-b81b-11e8-9054-fb77d5a6f5fb.png)

**Comment by mewa1024** [comment]
Design for the "New bot configuration" modal are on Invision.
Complete flow: [https://microsoft-fuse-design.invisionapp.com/d/main/#/projects/prototypes/15183213](url)

**Comment by tonyanziano** [comment]
Addressed in #898

**Comment by mewa1024** [comment]
@tonyanziano A couple things:
- When unchecked, the "Encrypt keys stored in your bot configuration..." check box should not hide the content below, but it should be grayed out with the placeholder text changed to "Your keys are not encrypted". That should also be changed for the Bot Settings modal.
- I think @justinwilaby implemented the URL field so that the warning was not always present: only check for the "api/messages" string after the field has been active and the user has stopped typing. If there is a validation error, replace the warning with the error.
- text: please change "MSA App Id" to "Microsoft App ID" and "MSA app password" to "Microsoft App password"
- text: please add the "Learn more." and link it to aka.ms/bot-framework-bot-file-encryption

Design comp (and start of the flow) here: [https://microsoft-fuse-design.invisionapp.com/d/main/#/console/15183213/315673909/preview](https://microsoft-fuse-design.invisionapp.com/d/main/#/console/15183213/315673909/preview)
