### ISSUE TITLE
Unable to connect bot emulator using local visual studio app. 

### ISSUE THREAD

**Issue by bhupendrarawat1973** [Microsoft/BotFramework-Emulator#91]
I am unable to connect with bot emulator using local visual studio app. getting the following error below:

 POST Refresh access token failed with status code: 400

**Comment by eanders-MS** [comment]
Hi @bhupendrarawat1973 Could you try clearing MSA appId and password from both sides (bot and emulator) and try again? It might be that one or both sides have an MSA misconfiguration.

Another possibility is you're using MSA credentials but working offline. MSA requires internet connectivity.

Here's a helpful auth debugging guide: https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/

**Comment by eanders-MS** [comment]
Closing for lack of response. If you're still seeing this problem, please open a new issue. Thanks.

**Comment by TheSachchin** [comment]
I am facing the same issue while working on local bot.
As per your response, removed appID and password from web.config and emulator still not able to proceed further.

**Comment by vansh187** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/40709014/54514175-70950780-497f-11e9-8032-b5dff029b986.png)
can u tell me how to resolve the error.

**Comment by vansh187** [comment]
i am not able to connect bot file with emulator

**Comment by tonyanziano** [comment]
Hello @vansh187 ,

For future reference, please open up a new issue instead of commenting on a closed, inactive issue if they are not related.

===

The "Unable to connect." message is supposed to show when the connection to the bot has been rejected due to bad credentials. However, I see that you are connecting to a local bot.

Can you possible upload the JSON inside of your .bot file? Make sure to remove any sensitive information beforehand if necessary (keys / secrets).
