### ISSUE TITLE
Emulator doesn't show deep link for ABS service

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#941]
## Version
![image](https://user-images.githubusercontent.com/17789481/46260262-87f73b80-c498-11e8-883d-fc682a8dd62a.png)

## Describe the bug
My bot file has an ABS record, and the services panel is not showing the ABS record and is not creating a deep link to the portal.

## To Reproduce
1. msbot connect bot … 
2. load bot file
3. Services section doesn't show Bot, there is no deep link'

## Expected behavior
Deep link to ABS portal 

[bug]

**Comment by justinwilaby** [comment]
#972 addresses the ABS listing in the services explorer. Since this service is connected to an endpoint, the ability to edit this service from the context menu has beed disabled.

**Comment by justinwilaby** [comment]
on hold pending design.

**Comment by mewa1024** [comment]
@tomlm @vishwacsena For the design of the pane, we decided not to separate the ABS service from the endpoint because it seemed redundant and potentially confusing:
![317169756](https://user-images.githubusercontent.com/39317542/46900628-f3a6b480-ce59-11e8-97a8-ff79def73a71.png)

Would this be sufficient?

The complete flow is on Invision: [https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/15012340](https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/15012340)
