### ISSUE TITLE
Auth: closing the Emulator application blocks on Azure sign out

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/BotFramework-Emulator#975]
Steps:

- Sign in to azure
- Close emulator using the window's cross
- You'll get a popup from auth saying something like "its a good idea to close all browser windows"
- At this point, you can ONLY exit emulator if you wait 10 seconds without touching anything
- If I close the auth popup (which is my reflex when I want to close and get out) emulator doesn't close at all!

I should't need to wait 10 seconds to close the application.

**Comment by justinwilaby** [comment]
This is by design. There is no way to know programmatically when Azure has completed the sign out so it is on a 5 second timeout once the first redirect is detected. I would like to implement the removal of the cookies and session data that remembers a previous login when the emulator is closed but this could have an impact on other areas of the app since session data and cookies are individually identifiable and must all be removed.

**Comment by carlosscastro** [comment]
I don;t think it is a great user experience. Let's talk through it on the Friday standup and figure out what we can do :)

**Comment by carlosscastro** [comment]
To get started, we could investigate a bit on some event that is more precise on when the azure sign out was completed than the  current 5 second timeout + 'page-title-updated' handling.

**Comment by justinwilaby** [comment]
Normally, a redirect to a `localhost` address occurs when logout completes but this was found to be unreliable so a 5 second timeout was a good failsafe measure and became the only reliable way to ensure this logout window would not hang around longer than it should. I tried several approaches and none were 100% reliable so I stuck with the timeout. The easiest way to fix this would be to remove the cookie and session data from disk. This also means there would be no need to launch the logout window and logging out would be immediate. I'm a bit hesitant of this approach since it may affect other areas of the app including community contributed extensions that might set or read cookie data.

**Comment by carlosscastro** [comment]
Yes, deleting the cookie entirely does not seem like the best choice. Also, this issue is P2 or P3 so a long investigation at this point is probably not worth!

I might timebox 2 hours of my time and see if I can get it working and otherwise add to backlog. Let's discuss in standup, but I don't think this is our highest priority.
