### ISSUE TITLE
Emulator - Tabs and command bar are using the wrong font and styles

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#993]
## Version
4.0.41504 - Windows

## Describe the bug
The tabs are using Arial instead of Segoe UI.

## To Reproduce
1. open a bot, look at the tab for an endpoint.
2. Click on a LUIS trace message. The Train and Publish buttons in the LUIS inspector are also using the wrong font.

## Expected behavior
Should be Segoe UI.
Design specs are on Invision:
[Light theme](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/320103604/preview)
[Dark theme](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/320103606/preview)
[High contrast them](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/320103605/preview)

## Screenshots
![image](https://user-images.githubusercontent.com/39317542/47049084-1fbf7f80-d151-11e8-8f36-365dc404e898.png)

![image](https://user-images.githubusercontent.com/39317542/47049245-965c7d00-d151-11e8-84b3-1bdc777dd3eb.png)

[bug]

**Comment by tonyanziano** [comment]
I've been looking into this. It looks like the relative paths to the `woff2` font files aren't being processed properly by our Webpack loaders. Instead of producing some data url like:

`src: url(data:application/woff-2;[SOME-HASH].woff2);`

it's trying to load `localhost:3000/[SOME-HASH].woff2` which doesn't exist in the packaged version because localhost:3000 is our webpack-dev-server and isn't running. I've at least narrowed down the localhost:3000 to the `publicPath` property in our `webpack.config.js`, but I'll continue investigating the issue of the data url not being generated.

**Comment by justinwilaby** [comment]
Webpack is not setup to generate data urls for anything over 8k. We can increase this limit or just use a file path for production builds.
